### PR TITLE
Track RandomSpawner origin of replaced things

### PR DESCRIPTION
**Pull request by wallabra**
This only applies to `RandomSpawner`s at the moment.

This allows mods to see the class of the original map thing that eventually led to a thing being spawned, to better interface with randomizer mods and the like.

A good usage example can be seen [here](https://codeberg.org/wallabra/AI-Director/pulls/4): if a Zombieman is replaced by a `RandomSpawner` capable of producing 5 other variants by a replacer mod using `RandomSpawner`, this change in AI Director would allow it to see the original `RandomSpawner` and guarantee access to all 5 variants, even in a level with only 1 initial Zombieman (so other types could spawn on, e.g., >100% start spawn factor, or in continuous spawns).

### CODE REVIEW

**Comment by wallabra** [comment]
This PR would produce this `gzdoom.pk3` (renamed to ZIP because GitHub), which has been crafted to be monkeypatched into existing GZDoom v4.12.2m installations (for testing, etc): 
[gzdoom.zip](https://github.com/user-attachments/files/16701161/gzdoom.zip)

**Comment by MajorCooke** [comment]
There's no reason to put this on Actor, just make this part of RandomSpawner itself. Also, please keep the coding style the same as the rest of the engine.

**Comment by RicardoLuis0** [comment]
and is there a need to add a new field to actor just for this? IIRC you can iterate over map-placed random spawners on `WorldLoaded`, they only repace during the first tick on `PostBeginPlay` (BeginPlay isn't called on map-placed things)

**Comment by wallabra** [comment]
That sounds like boilerplate that would have to be repeated for every mod interested in tracking RandomSpawner cause-effect chains. I agree there probably is a cleaner way, though...

**Comment by wallabra** [comment]
I'll go think about that and come back with a better idea. Thank you! :)

**Comment by RicardoLuis0** [comment]
> I'll go think about that and come back with a better idea. Thank you! :)

might be a good idea to use an event instead, ex. `ActorReplaced(class<Actor> original, Actor replacement)`

**Comment by wallabra** [comment]
> > I'll go think about that and come back with a better idea. Thank you! :)
> 
> might be a good idea to use an event instead, ex. `ActorReplaced(class<Actor> original, Actor replacement)`

Maybe, but mods still have to track what class each actor replaced, which also gets complicated when an actor has a multi-step replacement chain (e.g. due to `RandomSpawner`), vastly increasing code complexity on the modder's end.

That is, unless `ActorReplaced` somehow keeps track of which type an actor was on map load (the first type replaced by it, rather than the type it is replacing immediately), which in the engine end would probably done by a tracking variable like `originSpawner`... and we're back to square one!

**Comment by RicardoLuis0** [comment]
> That is, unless `ActorReplaced` somehow keeps track of which type an actor was on map load (the first type replaced by it, rather than the type it is replacing immediately), which in the engine end would probably done by a tracking variable like `originSpawner`... and we're back to square one!

yes, but that can be done in randomspawner itself, making it much lighter and simpler

**Comment by wallabra** [comment]
> > That is, unless `ActorReplaced` somehow keeps track of which type an actor was on map load (the first type replaced by it, rather than the type it is replacing immediately), which in the engine end would probably done by a tracking variable like `originSpawner`... and we're back to square one!
> 
> yes, but that tracking can be done in randomspawner itself instead of in actor, making it much lighter and simpler

I assume `RandomSpawner` instances are destroyed immediately after map load, and thus would be inaccessible from the perspective of, say, `EventHnadler::WorldThingSpawner`. While I agree that would be a cleaner solution, these instances would have to linger. Ideally it would be clear that they are in a "consumed" state.

**Comment by RicardoLuis0** [comment]
> I assume `RandomSpawner` instances are destroyed immediately after map load, and thus would be inaccessible from the perspective of, say, `EventHnadler::WorldThingSpawner`. While I agree that would be a cleaner solution, these instances would have to linger. Ideally it would be clear that they are in a "consumed" state.

The order goes: `WorldLoaded` -> `PostBeginPlay` -> `WorldThingSpawned`, and map-placed RandomSpawners do the replacing in `PostBeginPlay` so you can check them before they do any replacing if you do it from `WorldLoaded` (dynamically created randomspawners do their replacing in BeginPlay, so there isn't really a way to get in between there unfortunately, but that can still be fixed like i said with an `ActorReplaced` event that works directly with the random spawners, instead of adding fields to actors)

**Comment by wallabra** [comment]
That's fair, I'm also thinking about changing the `RandomSpawner` code to update a singleton object.

**Comment by wallabra** [comment]
(Tests pending)

**Comment by RicardoLuis0** [comment]
i still don't think this is a good solution -- any tracking can and should be done _only_ by mods that need the relevant data, all that's needed by the engine is an event to signal when replacements happen

**Comment by wallabra** [comment]
The engine is losing information about map start if it doesn't. I don't know if such behaviour should be left up to mods. This could be made an optional feature.

**Comment by wallabra** [comment]
Fair enough. I'll probably just make an event for when a mobj is replaced, and I'll move the tracking code elsewhere.

I still want it to be in some sort of optional utils library, to reduce the amount of duplicate code across mods.

**Comment by Boondorl** [comment]
I'm not sure I understand the use case for this. Is it solely to detect if something was spawned by a RandomSpawner? The example makes it seem like getting the RandomSpawner's list of monsters is desired, but there are much more trivial ways to do this such as iterating through all classes and storing classes marked as a monster that aren't replaced. This is something that mod itself should be handling in my opinion and not something baked into the engine.

**Comment by RicardoLuis0** [comment]
> I'm not sure I understand the use case for this. [...] The example makes it seem like getting the RandomSpawner's list of monsters is desired.

It's the opposite -- it's for getting the original randomspawner that created a particular actor

**Comment by Boondorl** [comment]
> It's the opposite -- it's for getting the original randomspawner class that created a particular actor

That was my take away, but it seemed they wanted this so they could get the rest of the monsters the spawner has. My thoughts are that these kinds of mods should simply be looking through the Actor classes for valid monsters, which can be done by getting its default, checking `bIsMonster`, and seeing if something replaces it. This kind of system can be extrapolated to any kind of Actor type e.g. items. Relying on any kind of RandomSpawner is bad practice because their behavior can be arbitrarily changed which is impossible to account for in a system like this.

**Comment by wallabra** [comment]
> > It's the opposite -- it's for getting the original randomspawner class that created a particular actor
> 
> That was my take away, but it seemed they wanted this so they could get the rest of the monsters the spawner has. My thoughts are that these kinds of mods should simply be looking through the Actor classes for valid monsters, which can be done by getting its default, checking `bIsMonster`, and seeing if something replaces it. This kind of system can be extrapolated to any kind of Actor type e.g. items. Relying on any kind of RandomSpawner is bad practice because their behavior can be arbitrarily changed which is impossible to account for in a system like this.

This seems to ignore the fact that a mod might want to see what kind of monsters (or even non-monster classes, like Items) could possibly be spawned within a level in its initial configuration, not every class there is as a whole.

**Comment by Boondorl** [comment]
Then the `CheckReplacement()` event can be used. Check to see if the replacement is a spawner and if it is, store any necessary information from there.

**Comment by wallabra** [comment]
> Then the `CheckReplacement()` event can be used. Check to see if the replacement is a spawner and if it is, store any necessary information from there.

Thank you. I still think some common utility for this should be provided in a library somewhere, either by GZDoom or in some centralized repository that has an utility that allows fetching modules online.

**Pull request closed without merging**
