### PR TITLE
Morphing Rework

### PR DESCRIPTION
**Pull request by Boondorl**
New year new me (literally). This is a total overhaul to ZDoom's infamous morphing system that's long been plagued with issues. In particular, the ability to work with it from ZScript is extremely frustrating since almost every call to `Morph()`/`Unmorph()` (the main virtual functions) is missing, the regular morphing virtuals can't really be tweaked due to `Substitute()`, dealing with monster classes is a nightmare since either everything inherits from MorphedMonster or you use a mixin to make two base classes, and `Substitute()` itself is just plain horrible. Not to mention the amount of precarious maintenance that comes from trying to override behaviors as-is and the amount of things GZDoom seemingly doesn't use for zero reason (like the `Alternative` pointer literally made for this).

This is a core feature in 2 of the 4 main Doom engine games. It deserves better than this, and so it shall be. There's probably too much stuff to realistically go into detail, but here's the main highlights:
* `Substitute()` has been replaced with `MorphInto()`. This function emulates the most prominent gameplay changes from `Substitute()` but does so in a way that's far safer than what GZDoom currently does. This does mean some "automated" pointer management will be removed and I understand this will likely mess with some niche situations, but I think going forward we're just going to have to accept that, like networking, morphing will require some extra effort from the modder to fully support. One of the goals of this update was making that as smooth as possible.
* Better gameplay barriers. `MorphInto()` comes with improved conditional checks for average gameplay to help with morphing management. This includes bugfixes to how players can morph (previously an oversight allowed them to change into MorphedMonsters and vice versa), improved safety on players and morphed Actors in general, and safety checks for items. Some necessary management outside of pointer swapping is now also handled, like transferring items, swapping player pointers where necessary, and handling `Alternative` and the `UNMORPHED` flag. The goal here is mainly to provide a bare-minimum function to make morphing coherent independent of overrideable behavior.
* On that note, MorphedMonster is no longer required. All Actors are now capable of properly being morphed.
* More consistency. `Alternative` is now always used and morphing logic has been changed to only call on Actors that are currently morphed (and not their dummy Actors). This gives modders a better idea of exactly when something is happening which is much needed. Extremely important behaviors like killing dummy Actors and destroying them have been built into the engine itself, where it should be. These are not things that should be left up to modders to figure out themselves lest tons of dangling Actors be left around.
* Rewrites of all the functionality for improved readability and reliability. This also fixed some edge case bugs like solid settings of morphed Actors being messed with when trying to collision test them and missed property and flag assignments. Morphing related properties have been given their own fields instead of cannibalizing things like `special2`, freeing these up again for any special behaviors in mods.
* Teleport fogs are no longer mandatory. I have no idea why this was never optional to begin with but for some reason `"TeleportFog"` was being brute forced across the board.

I'm putting this up as a draft to start because there's a ton of behaviors related to morph flags that aren't exactly easy to verify so testing will need to be done. However, I hope this can get the ball rolling on turning morphing into a proper engine feature rather than something duct taped onto it to get Heretic and Hexen functioning.

### CODE REVIEW

**Comment by EmeraldCoasttt** [comment]
Would this make it possible for players to morph when they're invulnerable? (is it already possible and I'm just stupid?)

**Comment by Boondorl** [comment]
You kind of could but it was functionally broken. Normally the player can only morph themselves when invulnerable and only if the morph style flag is set to allow it, but this never actually worked because morph projectiles wouldn't actually pass the owning player making it always skip the check. That's since been fixed but it's still locked to only the player. A new flag could be added that allows bypassing invuln checks

**Comment by EmeraldCoasttt** [comment]
That would be really good for scenarios where morphing is a power up rather than a power down

**Comment by Boondorl** [comment]
Gonna undraft this as I now consider it ready for merging. The last of the issues have been cleaned up and most of the important flags (new ones included) have been tested and verified.

**Comment by RicardoLuis0** [comment]
i've just taken a look and it seems all ok

**Pull request merged**
