### PR TITLE
- add freezetics actor property

### PR DESCRIPTION
**Pull request by madame-rachelle**

### CODE REVIEW

**Comment by madame-rachelle** [comment]
Example use case: https://cdn.discordapp.com/attachments/338381602952445952/1011657554113347675/floattime_freezetics.pk3

**Comment by MajorCooke** [comment]
Beautiful. This will actually be perfect for DE4D with the ice bomb.

**Comment by madame-rachelle** [comment]
Unfortunately it might be a bit overkill with the ice bomb. You'd better increment the .tics field instead (which already exists) - this field fully stops an actor, even with momentum. It can freeze projectiles in place.

**Comment by MajorCooke** [comment]
Oh I know. It's actually still perfect.

**Comment by OrdinaryMagician** [comment]
Oh this sounds extra useful for a "localized time stop" spell I want to add to a future project.

**Pull request merged**
