### PR TITLE
Remove linked list from particles

### PR DESCRIPTION
**Pull request by RicardoLuis0**
Refactors out the linked lists from the particle system, uses an array for normal particles and a deque for replaceable particles.

(This also adds a `stat particles` command to show the current number of particles)

### CODE REVIEW

**Comment by prof-hastig** [comment]
std::deque? I once read that on MSVC it is so horribly implemented that it often does one allocation per element. That doesn't sound efficient.

**Comment by Cacodemon345** [comment]
I'm not aware of any other alternate std::deque-like implementations that aren't a part of browser code outside https://github.com/slavenf/sfl-library. This may require a homegrown implementation.

**Comment by RicardoLuis0** [comment]
> std::deque? I once read that on MSVC it is so horribly implemented that it often does one allocation per element. That doesn't sound efficient. Some info here: https://bugs.chromium.org/p/chromium/issues/detail?id=674287 In general: All std:: containers except vector flat out suck.

it can handle 250 SPF_REPLACE particles being created per tick just fine at 65k particles, while just using TArray chugs to a crawl -- and since it works well enough, i don't see the need to pull in a separate deque implementation

**Comment by prof-hastig** [comment]
> > std::deque? I once read that on MSVC it is so horribly implemented that it often does one allocation per element. That doesn't sound efficient. Some info here: https://bugs.chromium.org/p/chromium/issues/detail?id=674287 In general: All std:: containers except vector flat out suck.
> 
> it can handle 250 SPF_REPLACE particles being created per tick just fine at 65k particles, while just using TArray chugs to a crawl -- and since it works well enough, i don't see the need to pull in or write a separate deque implementation

Meanwhile 10 years in the future: "Why does my mod with 10000 SPF_REPLACE particles become so slow...?" 
That's the curse of "good enough" despite knowing it's not actually good.

**Comment by RicardoLuis0** [comment]
if that becomes an issue in the future, the container can be swapped in the future, for now I've tested it to reasonable limits and it performed ok.

**Comment by coelckers** [comment]
std::deque really sucks, we got so different implementations that it's pointless to use in performance critical situations. This just seems to use it as a FIFO queue so the only question is, is there any risk of reallocation while elements are being used?

**Comment by RicardoLuis0** [comment]
> is there any risk of reallocation while elements are being used?
no there is not, what do you suggest as an alternative?

**Comment by coelckers** [comment]
I'll be honest here: I have no idea what you are trying to accomplish with the deque here. All you seem to do with it is pop off elements at the front and push new ones at the back for which I consider a simple array based ring buffer far more suited.

**Comment by MajorCooke** [comment]
The REPLACE flag for particles that I introduced is extremely slow to search for the oldest particle, so he introduced this to fix that issue.

**Comment by coelckers** [comment]
The way the deque gets uses still feels like code smell.

**Comment by RicardoLuis0** [comment]
> a simple array based ring buffer far more suited.

A ring buffer wouldn't work, because if the particle limit isn't reached, it grows in size instead of replacing

**Comment by prof-hastig** [comment]
After having a closer look at the deque code to think about something more efficient I don't think this code is correct in its current state.
If 'replaceable' means that the oldest particle is supposed to be recycled if the list is exhausted the way it handles deletion of particles does not work. It just copies the last entry of the deque to the one that got just freed if one particle expires, which alters the order by age. This would have to compact the entire array by moving everything down from the end, not just swapping a single entry in the list. In other words: When looking for the oldest particle to discard, it has to search the entire list for the oldest one as the order does not reflect age. Which ultimately makes deque the wrong container here because it sucks at moving content around.
Even so, 'oldest' is a poor metric here, it should pick the one with the shortest remaining life left.

**Comment by prof-hastig** [comment]
One other thing is also missing. If the max number of particles has been reached and a non-replaceable particle gets spawned it will fail, even if there's replaceable particles that could be deleted to make room.

**Comment by coelckers** [comment]
Good points. That would render the implementation quite a bit broken I'd guess.

**Comment by MajorCooke** [comment]
"

> Even so, 'oldest' is a poor metric here, it should pick the one with the shortest remaining life left.
No, it shouldn't. It's targeting the oldest as it should be, and this won't change.

**Comment by MajorCooke** [comment]
> Good points. That would render the implementation quite a bit broken I'd guess.

If you do anything about this, please do not change how replace targets the oldest particle. The REPLACE flag works perfectly as is! That's how I designed it, that's how it should be! Everyone is expecting it to be this way, and it'll decrease performance because it'll have to search through every particle to get the lowest lifespan.

**Comment by MajorCooke** [comment]
> Even so, 'oldest' is a poor metric here, it should pick the one with the shortest remaining life left.

Oldest particle in the current GZDoom system should absolutely not be changed. If that occurs, it'll significantly decrease performance. with what's currently implemented (here may be different)

**Comment by MajorCooke** [comment]
Another reason to keep it to oldest instead of lowest lifespan:

If a bunch of particles spawn and they have a lifespan of 35, and then you spawn the last free particle with a lifespan of 5, that newest particle will be targeted to be replaced. It'll look weird as hell and not what people expect.

**Comment by RicardoLuis0** [comment]
> It just copies the last entry of the deque to the one that got just freed if one particle expires, which alters the order by age. This would have to compact the entire array by moving everything down from the end

🤦‍♂️ i copied the faster despawn logic from the non-replaceable particles and didn't even think of the shuffling it did, yeah, i'll need to fix that

> One other thing is also missing. If the max number of particles has been reached and a non-replaceable particle gets spawned it will fail, even if there's replaceable particles that could be deleted to make room.

the same happens the other way, if there are no replaceable particles and you try to spawn one, it'll fail because there's nothing for it to replace, but unfortunately that is by design regards to how SPF_REPLACE works -- only replaceable particles can be replaced, and they can only be replaced by other replaceable particles

**Comment by MajorCooke** [comment]
Correction: ALL the particles are replaceable. None of them are non-replaceable. All it needs is the SPF_REPLACE flag, because you wouldn't want particle fountains replacing your special effects now, would you?

**Comment by RicardoLuis0** [comment]
> all particles are replaceable if SPF_REPLACE is used.

is that so? i must've misunderstood how it works then 👍

**Comment by MajorCooke** [comment]
Yes. The logic is simple: 

If SPF_REPLACE is present and the particles list is completely full, replace the oldest particle (which is already tracked at all times).

If the flag is absent and all particles are in use, do nothing.

**Comment by MajorCooke** [comment]
If you're wondering, [OldestParticle](https://github.com/ZDoom/gzdoom/pull/2173/files#diff-a07a9b22c39547707ab15c0b632709067d8f54123a3980836736aa950cbc14b4L657) is what tracks. Whenever a particle expires or is replaced, it automatically shifts to the next one. This way, it's easy to find, and super efficient.

**Comment by coelckers** [comment]
That would render the entire implementation of this PR pointless because what you describe requires a completely different approach. I think this needs to go back to the drawing board and redone from scratch.

**Pull request closed without merging**
