### PR TITLE
[BUGFIX] Fix Quat Conjugate/Inverse

### PR DESCRIPTION
**Pull request by RicardoLuis0**

### CODE REVIEW

**Comment by CandiceJoy** [comment]
How close is this to being ready for review?

**Comment by RicardoLuis0** [comment]
just needs some testing that the functions are working and doing what they should, i don't know much about quaternions so i can't verify anything

**Comment by CandiceJoy** [comment]
Issue is #1903

**Comment by coelckers** [comment]
This PR is unacceptable because it breaks the API. 
If we get a fix without that it will be accepted, unfortunately I don't even understand what's wrong here.

**Comment by Gutawer** [comment]
If I remember correctly, this was a crash caused by my implementation of `Inverse` and `Conjugate` using `PARAM_SELF_STRUCT_PROLOGUE` on a `DQuaternion`, which isn't correct because `Quat`s act like "`Vector4`"s as far as the VM/JIT is concerned? It worked on my machine when committing but I suppose this hit some form of implementation-defined/undefined behaviour. I feel like the proper fix here should be to make `Inverse` and `Conjugate` into opcodes, much like `OP_LENV3` etc.

**Comment by RicardoLuis0** [comment]
> This PR is unacceptable because it breaks the API. If we get a fix without that it will be accepted, unfortunately I don't even understand what's wrong here.

yeah, that's why i drafted it -- to replace it with a proper fix, but i kinda forgot to do that 😓

**Pull request closed without merging**
