### PR TITLE
[new feature, low priority] ZScript Struct Assignments + Static Function Pointers

### PR DESCRIPTION
**Pull request by RicardoLuis0**

### CODE REVIEW

**Comment by MajorCooke** [comment]
What are struct assignments?

**Comment by RicardoLuis0** [comment]
it lets you assign structs to each other, with `=`, ex.:
image
image
image

**Comment by MajorCooke** [comment]
And even make arrays of them? Amazing!

**Comment by MajorCooke** [comment]
Looking good so far, I look forward to its completion.

**Comment by RicardoLuis0** [comment]
it _should_ be completed, all i've tested myself worked, but it's still needs more testing to be sure (got merged into vkdisdain for testing)

**Pull request closed without merging**
