### PR TITLE
Add PreHandlePickup() for unconditional processing of received items

### PR DESCRIPTION
**Pull request by jekyllgrim**
Added functions: `PreHandlePickup()` and `CallPreHandlePickup()`

These function similarly to `HandlePickup()`/`CallHandlePickup()`, except they're called earlier in the chain and unconditionally. This will allow mod authors to process items universally in cases where the item can't be replaced and its `HandlePickup()` override returns true, blocking further processing. For example, this will allow to process powerups every time they're received.

`CallPreHandlePickup()` is also injected in `TryPickup()` of the Health class to allow processing of health pickups.

The return values (true/false/pass) utilize a new `EPreHandlePickupResult` enum added to Inventory.

### CODE REVIEW

**Review by coelckers — CHANGES_REQUESTED** [review]
Please do a clean reformat with 4 character tabs. Some of the additions indent with spaces which is not the project's style.

**Comment by coelckers** [comment]
The idea behind this is fine, but placing it into TryPickup may turn out to be a major implementation hassle for new actors, because TryPickup is an overridable function, and ideally such code should be in the non-overridable CallTryPickup function to ensure that it gets called uniformly for everything. I'm not sure if this will allow to handle it properly, though.

**Comment by jekyllgrim** [comment]
You're right, and I think this can be put on hold while I rethink the implementation a bit.

**Comment by jekyllgrim** [comment]
Closing this so I can rework it. The reworked version is likely going to be structured very differently, so there's no need to keep this around.

**Pull request closed without merging**
