### PR TITLE
AV1 IVF and AVIF decoding support

### PR DESCRIPTION
**Pull request by Cacodemon345**

### CODE REVIEW

**Review by coelckers — CHANGES_REQUESTED** [review]
The image loader should use simpler means to reject non-AVIF images. Read the first few bytes into a buffer and check yourself instead of calling the library right away, just as I did for WebP. This code otherwise gets run on virtually all data being loaded from WADs, Zips etc that cannot be identified by an earlier format.

**Comment by Cacodemon345** [comment]
Unfortunately it's not that simple, as AVIF like JPEG XL is a ISOBMFF format, which doesn't appear to mandate that the ftyp box be at the beginning of the file.

**Comment by kcat** [comment]
> Unfortunately it's not that simple, as AVIF like JPEG XL is a ISOBMFF format, which doesn't appear to mandate that the ftyp box be at the beginning of the file.

MP3 is the same way, an mpeg audio stream can technically be anywhere in a file and a parser only needs to find the frame headers (a lot of mp3 players can play mp3-in-wav files, without explicitly supporting it), but I don't think it's been much of a problem to require identification markers early in the file with such formats for GZDoom to use it (if not right at the front, then something like the first few hundred bytes that's quick to read and check).

**Comment by coelckers** [comment]
Actually, MP3 has always been a poor format to detect due to the weak specification, if not the worst of all. "My data can start anywhere in the file, you just got to find it" is certainly the very worst approach imaginable.
Seriously, such formats should be a thing of the past, yet from these committees we get the same shit all over again. Just put something in the first 4 bytes that clearly rules out any other format would do the trick. We could quickly reject anything clearly not in the given format and go on to the next.
JPEG XL is even worse than this and makes it a hassle to write a simple format detector that doesn't require an external library to provide the secret sauce to allow robust detection.

**Comment by coelckers** [comment]
BTW, I just checked out the AVIF init code to see how much of it runs before it finds out that the images is not the proper format. The answer is: Way too much, It sets up a large portion of the decoded infrastructure before starting to read from the file, so if the format ultimately can be done with a different header it will pose a major problem, not just for us. If we can take those first 12 bytes for granted, all will be well, but only then.

**Comment by coelckers** [comment]
I'm sorry, but I have to reject this PR because it increases executable size of a release build from 10 MB to 24 MB. That's simply too much for the provided functionality.

**Pull request closed without merging**
