### PR TITLE
Add Multi-Assign Declarations

### PR DESCRIPTION
**Pull request by RicardoLuis0**
`let [a, b, c] = Func();`
Example: [Test.zip](https://github.com/ZDoom/gzdoom/files/10269749/Test.zip)

### CODE REVIEW

**Review by coelckers — COMMENTED** [review]
Just one question: I see several asserts in this code. Can you guarantee that no possible script code can trigger these asserts? If not, they have to be made actual errors that need to be checked for.

**Comment by RicardoLuis0** [comment]
One of the asserts (`assert(ass->Sources->SiblingNext == ass->Sources);`) is also done in `AST_AssignStmt`, so i don't think it's something that regular code can trigger, and the other (`assert(Base[i]->ExprType == EFX_Identifier);`) is just a sanity check on the parser, the contents of the list _should_ only ever be identifiers, since that's the only thing the parser accepts for it, but the assert is in just in case

**Comment by RicardoLuis0** [comment]
wait no, i'll double check

**Comment by RicardoLuis0** [comment]
oh yeah, i'm wrong 😓

**Comment by RicardoLuis0** [comment]
ok, it's properly restricted now

**Pull request merged**
