### PR TITLE
Added QF_DAMAGEFALLOFF and damagemultiplier, thrustmultiplier, and damage properties to earthquakes.

### PR DESCRIPTION
**Pull request by inkoalawetrust**
This PR adds 4 new features to earthquakes:

- QF_DAMAGEFALLOFF: This flag makes the damage and actor thrusting earthquakes produce fall off with distance. It works exactly like how the distance falloff for the actual screenshake effect works*. So the _falloff_ property also needs to be given a value besides 0 for the falloff to work.
- damageMultiplier: This is a new property for earthquakes that acts as a multiplier for the damage they perform to players and actors. It can be used to make earthquakes more or less harmful, such as making a very strong earthquake do more damage. Default is 1.0 (Normal damage)
- thrustMultiplier: Like _damageMultiplier_, this property allows you to increase or decrease how much earthquakes push actors around. It can also be set to 0 to disable actor pushing entirely. Default is 0.5.
- damage: When this property is set to anything above 0, the earthquake will do the exact amount of damage specified, instead of the default randomized damage. This will also account for damage falloff and the damage multiplier.

In addition, since earthquake damage can now go to 0 or below, the damage is clamped to be at least one hit point when the victim is in the damage radius. So that damage falloff or a damage multiplier of 0 won't produce quakes that do no damage despite being within their damage radius. For the latter you can simply use the QF_SHAKEONLY flag.

Also, the code includes a fix that makes QF_AFFECTACTORS use an FMultiBlockThingsIterator instead of a ThinkerIterator, which stops the earthquake from trying to shake objects it shouldn't like items that are in actors' inventories.

[This PR also comes with this update to ACCs' definitions.](https://github.com/ZDoom/acc/pull/95)

An example map is also included, this map produces an earthquake with damage and thrust falloff, the earthquake also does exactly 3 damage, which is then multiplied by 2. And also produces very little pushing.

[Earthquake falloff example.zip](https://github.com/ZDoom/gzdoom/files/10368144/Earthquake.falloff.example.zip)

*Except that for damage and thrusting falloff, it uses the damage radius instead of the tremor radius.

### CODE REVIEW

**Comment by MajorCooke** [comment]
Merge conflicts prevent me from adapting this to QZDoom. Please fix them.

**Comment by inkoalawetrust** [comment]
Alright, I'll fix the merge conflicts with this PR and your decimal earthquake intensity sometime later. I'm currently busy with getting a live Linux installation running on my old PC.

**Comment by inkoalawetrust** [comment]
Okay, I made a new commit to the branch that fixes the merge conflicts.

**Comment by inkoalawetrust** [comment]
Okay, I've also fixed the decimal earthquake intensities not working with ACS.

**Comment by MajorCooke** [comment]
I'm postponing merging this into QZDoom until:
1. The next testing round is available (already have 15 PRs)
2. The merge conflicts are fixed

**Comment by inkoalawetrust** [comment]
halle-fucking-lujah I finally managed to babysit Git into actually letting me fix those stupid merge conflicts. You should be able to merge this into QZDoom now.

**Comment by inkoalawetrust** [comment]
Okay, @MajorCooke showed me on Discord that lines 195 and 198 on a_quake.cpp caused double-to-integer conversion warnings on the MSVC compiler (And presumably on GCC too, [can't find any warnings on the old compile checks though](https://github.com/ZDoom/gzdoom/actions/runs/3982266761).). So I've force pushed the last commit on the branch to fix those with explicit conversion to ints.

**Pull request merged**
