### PR TITLE
Update ZVulkan to latest version

### PR DESCRIPTION
**Pull request by dpjudas**
Updates ZVulkan to latest version, which includes a vk_mem_alloc update.
Also changes "vsync off" from mailbox to immediate present mode since otherwise it doesn't work in exclusive full screen.
And finally it fixes a scratch buffer alignment bug with the vk raytrace thing.

### CODE REVIEW

**Comment by coelckers** [comment]
This one's enough for me not to merge it:
"Also changes "vsync off" from mailbox to immediate present mode since otherwise it doesn't work in exclusive full screen."

What else does this change with regards to exclusive fullscreen? Is this mode now forced, or is it an option.
There's too many unknowns for me to blanketly merge it.

**Comment by dpjudas** [comment]
Exclusive full screen is optional, just like before, configured via that vk_exclusive_fullscreen CVAR which defaults to off.

I did also turn off mailbox for the non-exclusive mode, but that's because the mode isn't working on my computer with Nvidia's latest drivers. It locks it vsync for some reason (this also applies to what is currently on the master branch). I can enable it again for non-exclusive mode if you want. It will just mean I can't test speed stuff without patching GZD until NV fixes their drivers.

I'll look into the compile error thing ofc - didn't notice that it wasn't building there. :)

**Comment by dpjudas** [comment]
OK I rolled back the immediate/mailbox thing and fixed the compile error. That should clear your objections I hope.

We need someone on unix to confirm this PR works since, at least theoretically, something could have broken there. I don't anticipate any problems but the swap chain stuff in vulkan is just pure horror.

**Comment by OrdinaryMagician** [comment]
So far I'm not seeing anything break at all on Linux with these changes.

Changing vk_raytace at runtime still crashes on nvidia drivers, though. I'd say my suggestion to make it a latch CVar still stands.

**Comment by MajorCooke** [comment]
As this is a massive change, I'll bring this in for the next round of QZDoom testing after a bunch of the smaller PRs are knocked off.

**Comment by dpjudas** [comment]
This isn't a massive change - it only looks big because it updated vk_mem_alloc. The only reason it changes a lot of files is because some device properties moved (no actual change in logic, just a minor API adjustment).

I wanted a confirmation for it working on Linux mostly because the swap chain code changed and, while unlikely, there was at least a theoretical chance I could have missed something.

vk_raytrace remains an unsupported feature even with this PR. The bug fix wasn't the motivation for the PR - the swap chain adjustments were.

**Pull request closed without merging**
