### PR TITLE
- Fire the corona line trace to the center of the corona's height

### PR DESCRIPTION
**Pull request by nashmuhandes**
- Add some defaults to Corona that make most sense
- Add some documentation to the corona ZScript file

### CODE REVIEW

**Comment by coelckers** [comment]
Nice stuff overall, but there's one issue here that makes the feature rather unappealing as-is. Handling coronas by explicitly spawning new actors sounds very tedious and counterproductive.

It would be a lot better if they could be handled by dynamic lights through new feature extensions - so that they can just be added to the light definitions in GLDEFS. Since these are purely visual add-ons they should act like dynamic lights and not require spawning of a full actor for each corona effect.

**Comment by nashmuhandes** [comment]
> Nice stuff overall, but there's one issue here that makes the feature rather unappealing as-is. Handling coronas by explicitly spawning new actors sounds very tedious and counterproductive.
> 
> It would be a lot better if they could be handled by dynamic lights through new feature extensions - so that they can just be added to the light definitions in GLDEFS. Since these are purely visual add-ons they should act like dynamic lights and not require spawning of a full actor for each corona effect.

The decision to not attach them to dynamic lights was deliberate - there's no way to use coronas for baked lightmaps/ZDRay if the coronas were attached to dynamic lights. ZRay's static lights do not spawn in the world when the map is loaded. Do you have any suggestions?

**Comment by nashmuhandes** [comment]
And another reason why an actor was chosen was so that the corona sprites would be visible in Ultimate Doom Builder's visual mode, which IMO is important as the mapper needs to know where to precisely place the coronas.

Regardless, I'm open to suggestions on how to improve the system.

**Comment by dpjudas** [comment]
We could just let the static light spawn I guess. It is not like it will have any performance impact worth mentioning.

**Comment by coelckers** [comment]
The actor based approach proved to be a problem for dynamic lights - I'd expect the same here in the end.
What I'd like to see is something similar to how dynamic lights work:

You can place actors in the map, but they are inert and only serve as reference to an engine side object.
Light definitions also spawn such an engine side object but do not need their separate actor as they can reference the one that spawned them from its light definitions.

What this entails is essentially:

a) coronas can be defined in GLDEFS and attached to actor classes.
b) both these and map placed coronas spawn an internal engine object that is being used by the renderer to decide where to draw a corona.

We could then define a standard definition for adding coronas to the internal objects as an additional autoload

**Comment by Talon1024** [comment]
How would one customize the sprite used for a corona?

**Comment by coelckers** [comment]
At the moment it's the sprite in the actor's spawn state.

**Pull request closed without merging**
