### PR TITLE
Add support for embedded offsets in TGA images

### PR DESCRIPTION
**Pull request by Cacodemon345**
This PR adds support for embedded offsets in TGA images by using the TGA 2.0 developer area extension.

The developer area of the image file starts with `grAbOffset`, followed by 2 little-endian 16-bit signed integers, first one describing X offset, and second one describing Y offset.

### CODE REVIEW

**Comment by madame-rachelle** [comment]
The only thing I am not too fond of is the fact that these are all using png's naming conventions. I'd rather not name something `grAb` without significant technical reason to do so.

**Comment by Cacodemon345** [comment]
That name's used for uniqueness purposes, since checking Software ID of the file is impractical.

**Comment by madame-rachelle** [comment]
I'd really much rather name it something fit-to-purpose, i.e. OriginPoint or ZeroPoint. I'll leave ultimately the final decision to Graf, but that is my thoughts on it.

**Comment by coelckers** [comment]
Do we need this? I consider TGA deprecated, support was only added for some old model skins and skybox textures but not really for producing new content. As it stands now we can at any point decide to switch to stb-image for the format, but if we add custom information that route is closed.

**Comment by Cacodemon345** [comment]
Our TGA implementation doesn't rely on libraries to function though, so I see no benefit in switching away from home-made implementation in this case.

**Comment by coelckers** [comment]
You did not answer the main question: Why do we need this? AFAIK there's no tools being able to set it and I wouldn't ever expect such tools to appear.

**Comment by Cacodemon345** [comment]
Tools consider the extension area of TGA files enough for their metadata information, and generally don't really bother with developer area of those files because those don't often see the need for it.

And as for the main question, it's for convenience purposes; it's actually extensible unlike QOI and no editors will ever bother to deal with developer areas. Plus it removes the need to define offsets in TEXTURES lump. And of course the exact same reasons why PNG has `grAb`.

**Comment by coelckers** [comment]
So is PNG. Why do you need another image format?

**Comment by Cacodemon345** [comment]
I mean, support for TGA already exists in this engine, and it's relatively simpler to decode it barring pixel and scanline order as compared to QOI.

**Comment by coelckers** [comment]
Ok, since you still haven't answered my question, I am closing this now. A new feature needs to have a point. This one doesn't.

**Pull request closed without merging**
