### PR TITLE
[bugfix] Major fixes to A_ChangeModel, fixes memory leaks, segfaults, etc

### PR DESCRIPTION
**Pull request by RicardoLuis0**

### CODE REVIEW

**Comment by MajorCooke** [comment]
This would be of great help.

**Review by coelckers — CHANGES_REQUESTED** [review]
Have you actually verified that this is ok?

template<> struct native_is_valid<FName> { static const bool value = true;  static const bool retval = true; static_assert(sizeof(FName) == sizeof(int)); };

Last time I checked MSVC passed this by reference and not by value so FName is not acceptable as valid argument for native functions!

**Comment by RicardoLuis0** [comment]
> Have you actually verified that this is ok?

I tested it and it worked ok, but i'll double check

**Comment by RicardoLuis0** [comment]
seems like it would be fine on msvc at least
image
> https://learn.microsoft.com/en-us/cpp/build/x64-calling-convention?view=msvc-170

**Comment by RicardoLuis0** [comment]
on Linux seems to be the same
image
image
image
> https://refspecs.linuxbase.org/elf/x86_64-abi-0.21.pdf

**Comment by RicardoLuis0** [comment]
not sure about the Apple ABI, but it should be similar as well

**Comment by coelckers** [comment]
The issue here is that older MSVC versions did not pass these by value and it caused crashes in the JIT interface.
This is why I am careful here.

**Comment by RicardoLuis0** [comment]
this was compiled and tested on VS2019 with the JIT enabled, and since gzdoom compiles with C++17, it requires a relatively recent version of MSVC, so i don't think this would be an issue

**Comment by RicardoLuis0** [comment]
removed FName parameters, hopefully this can get in now

**Comment by madame-rachelle** [comment]
If this tests out okay is it safe to merge? It'd really be a shame ot leave this PR in limbo. Also, do we really care about MSVC versions older than 2019?

**Comment by RicardoLuis0** [comment]
> If this tests out okay is it safe to merge?
it's been tested with a mod that heavily uses A_ChangeModel during writing, and it's already merged in the disdain engine fork since a few days ago with no apparent issues ( MischiefDonut/VkDisdain#20 )

**Comment by MajorCooke** [comment]
I suggest merging it. If things go seriously wrong, devs can always revert it.

**Comment by inkoalawetrust** [comment]
Just merge it already.

**Comment by MajorCooke** [comment]
That's not a very good way to persuade someone to merge something, bud. If anything, that's quite _dissuasive_. I suggest you retract your statement. **Immediately.**

**Comment by inkoalawetrust** [comment]
Sorry, I just meant that it should be merged already, since it has already been merged into Disdain with apparently little issue. And also it could be revoked until the next release if something IS wrong.

**Comment by MajorCooke** [comment]
@madame-rachelle Nash has committed on Discord that there's been no problems. Graf has stated that it's up to those who use models to do this. As Nash is one of them, I trust him and Shiny Metagross.

**Comment by madame-rachelle** [comment]
I've gone ahead and did the merge. I haven't seen any reason to believe that this will cause any real problems, and if it does we'll find out soon enough anyway.

**Comment by RicardoLuis0** [comment]
taking a look at #2097

**Pull request merged**
