### PR TITLE
add set/get plane reflectivity

### PR DESCRIPTION
**Pull request by kevansevans**
Adds both SetPlaneReflectivity and GetPlaneReflectivity to Sector structs

### CODE REVIEW

**Review by coelckers — CHANGES_REQUESTED** [review]
Please move the exceptions out of the engine core into the VM wrapper functions.

**Comment by kevansevans** [comment]
Applied change as requested

**Comment by RicardoLuis0** [comment]
this last commit seems to have added major formatting changes to r_defs

**Comment by kevansevans** [comment]
I did not notice that and am tremendously confused as to where it came from. Should be cleaned up now.

**Pull request merged**
