### PR TITLE
Switch PNG loading/saving to libpng to get rid of edge case bugs in the manual loading/saving code

### PR DESCRIPTION
**Pull request by RicardoLuis0**
Has been tested by myself with PNG-heavy mods

### CODE REVIEW

**Comment by coelckers** [comment]
For me the libpng dependency is unacceptable, especially in binary form. This also requires linking real zlib which we already got rid of. The .dll version which you appear to use is also linked against the shared runtime library which pulls in other unwanted dependencies if people don't have it installed already.

Have you had a look at SPNG (https://libspng.org/)?
That one looks a lot less awful than libpng and can be embedded in source form easily.

**Comment by RicardoLuis0** [comment]
and does it support all edge cases (ex. 16 bits per channel PNGs) properly like libpng?

**Comment by RicardoLuis0** [comment]
seems it can't do BGRA, and that the api for reading user chunks is a lot more convoluted

**Comment by madame-rachelle** [comment]
Sometimes manually really is the best way to handle things. We probably should make a special texture type that can handle 16 BPC textures, because they will become much more relevant when HDR screens start becoming the norm. And then the loader can just load the data right into that.

**Comment by RicardoLuis0** [comment]
> seems it can't do BGRA, and that the api for reading user chunks is a lot more convoluted

and seems like it can't write files from images that are upside down either

**Comment by RicardoLuis0** [comment]
(and no, it doesn't require linking against zlib from gzdoom, it only needs including the _dll_ for zlib)

**Comment by Boondorl** [comment]
> Sometimes manually really is the best way to handle things.

It really isn't the best solution here, I have absolutely no idea why ZDoom is using its own manual loader instead of something standardized. Have we 100% verified all of Graf's concerns here? I don't think we should be rejecting PRs by spitballing things that could be wrong.

**Comment by RicardoLuis0** [comment]
> Have we 100% verified all of Graf's concerns here? I don't think we should be rejecting PRs by spitballing things that could be wrong.

embedding libpng like dpjudas wanted to would alleviate most of them pretty sure, i think miniz is fully api-compatible with zlib?

**Comment by coelckers** [comment]
> (and no, it doesn't require linking against zlib from gzdoom, it only needs including the _dll_ for zlib)

Precisely what we constantly tried to avoid with external code. Turning GZDoom into a dll mess like those primarily developed on Linux sound like a not such good idea.


> > Have we 100% verified all of Graf's concerns here? I don't think we should be rejecting PRs by spitballing things that could be wrong.
> 
> embedding libpng like dpjudas wanted to would alleviate most of them pretty sure, i think miniz is fully api-compatible with zlib?

You will have to make some minor adjustments to libpng - and of course clean out all that atrocious ancilliary garbage the source ships with.

**Comment by madame-rachelle** [comment]
> It really isn't the best solution here, I have absolutely no idea why ZDoom is using its own manual loader instead of something standardized. Have we 100% verified all of Graf's concerns here? I don't think we should be rejecting PRs by spitballing things that could be wrong.

The thing is, PNG is a very simple format. All these "edge cases" are things that can be corrected in the loader - because I promise you, there's a very limited number of them, and there will ever be a limited number of them due to the lack of complexity of the format itself. There really is nothing wrong with rolling your own solution to stuff like this if you can keep it simple and self-contained. The "edge cases" problem is only a problem with lack of implementation, nothing more. I am not against adding a library other than the responsibility of having to keep it updated - but quite honestly, it seems like a lot more effort for something that ultimately doesn't seem to provide much gain.

**Comment by coelckers** [comment]
The current PNG code will fall back to stb-image for 16 bit per channel formats. But there's no way a savegame can get one of those unless being manually put in.

**Pull request closed without merging**
