### PR TITLE
ID24 interlevel lumps implementation

### PR DESCRIPTION
**Pull request by Cacodemon345**
This PR implements ID24's interlevel lumps format, which is needed for intermission screens for Legacy of Rust mapset.

### CODE REVIEW

**Review by coelckers — CHANGES_REQUESTED** [review]
Just from looking over the code there's 3 minor things that need changing:

1. Make the new feature available to regular MAPINFO and ZMAPINFO as well, not just UMAPINFO.
2. G_InitNew is not the right place to set the secret level flag. This should be done right after parsing all MAPINFOs. G_InitNew will be called each time a game starts.
3. The JSON parser for intermissions should not abort - if it throws an error, catch it, print it to the console and instead show the default intermission screen

**Comment by Cacodemon345** [comment]
Done.

**Comment by coelckers** [comment]
The animations of the second episode do not play. Is this the result of what people were talking about on Doomworld regarding the level numbers?

If so, the format is indeed broken by design, any chance to do something about it?

**Comment by Cacodemon345** [comment]
The animations of the second episode assume that the level numbers will restart from 1 with each episode defined.

The first map of the second episode is defined with an episode field in the UMAPINFO as expected, but the port seems to assume that the level numbers for the interlevel lumps specified with it and afterward will restart from 1 and keep incrementing with each map definition.

It can be easily dealt with by adding an additional field to account for this problem that also follows the expected behaviour and make it work again.

**Comment by coelckers** [comment]
That's what I meant. The spec is broken, plain and simple - making such assumptions is not good.

**Comment by Cacodemon345** [comment]
I wouldn't say it's broken; it's basically an assumption made because the base UMAPINFO spec has no provisions for arbitrary (or implicit) map numbers. It at least can be dealt with by adding two fields to the internal map structure, one indicating the episode number and the other one indicating the map number within the episode. For MAPINFO/ZMAPINFO using these interlevel lumps, those follow normal rules for level numbers.

It does suck, sure, but nowhere near as a deal breaker as the TRANMAP stuff in the ID24 specification is, and at the very least can be worked around.

**Comment by Cacodemon345** [comment]
Marked as draft in anticipation of the official level number behaviour getting amended in future patches.

**Comment by coelckers** [comment]
I merged this manually and added some band aid for the levelnum. Let's just hope this gets fixed for real in the spec.

**Pull request closed without merging**
