### PR TITLE
Convert the entire image backend infrastructure to be animation-friendly

### PR DESCRIPTION
**Pull request by Cacodemon345**
This PR converts the entire image backend infrastructure to be animation-friendly, to prepare for supporting animated images.

### CODE REVIEW

**Comment by Cacodemon345** [comment]
JPEG XL isn't available in Ubuntu 20.04 LTS, but sure, it can be PR'd as an optional feature.

**Comment by coelckers** [comment]
The Ubuntu 20.04 LTS users have to use vcpkg to build a working version if they need support.

**Comment by Cacodemon345** [comment]
JPEG XL PR is there now, and as an optional feature.

**Comment by coelckers** [comment]
merged manually

**Pull request closed without merging**
