### PR TITLE
Allow summon to work with visual thinkers

### PR DESCRIPTION
**Pull request by RicardoLuis0**

### CODE REVIEW

**Comment by MajorCooke** [comment]
Don't forget `remove` command!

**Comment by RicardoLuis0** [comment]
eh, that's not as useful as summon, so can always be added later

**Comment by MajorCooke** [comment]
I do think it should be done regardless for testing purposes. Please?

**Comment by RicardoLuis0** [comment]
like i said, i'll look into it after, i'm PRing this because i've added it for my own testing, if you need remove now, feel free to add it, if not, just wait, i'll probably add it later

**Pull request merged**
