### PR TITLE
Add system for modular SBARINFO

### PR DESCRIPTION
**Pull request by BinarryCode**
Doing this to keep parity with [a Zandronum patch request.](https://zandronum.com/tracker/view.php?id=4303)
- Added new top level "AppendStatusBar", allowing for extra SBARINFO code to be added to custom SBARINFO definitions.

### CODE REVIEW

**Comment by MajorCooke** [comment]
Is this what I think it is? So this would allow attaching multiple status bars on top of each other?

Does this allow covering ZScript too?

**Comment by MrRaveYard** [comment]
This seems to be "I don't want to copy+paste the entire SBARINFO just to add one thing to the screen" solution.

**Comment by RicardoLuis0** [comment]
> This seems to be "I don't want to copy+paste the entire SBARINFO just to add one thing to the screen" solution.

nah, pretty sure this is for addon mods that don't replace custom huds, being for zandro and all

**Comment by prof-hastig** [comment]
and so a supposedly deprecated feature continues to live on...

**Review by RicardoLuis0 — CHANGES_REQUESTED** [review]

**Review by RicardoLuis0 — APPROVED** [review]

**Comment by RicardoLuis0** [comment]
> and so a supposedly deprecated feature continues to live on...

if such feature is extended in other ports, the least we can do is keep parity

**Comment by BinarryCode** [comment]
Any progress on this? Zandro devs are currently waiting on if it gets merged or not.

**Comment by RicardoLuis0** [comment]
> Any progress on this? Zandro devs are currently waiting on if it gets merged or not.

SBARINFO is not actively developed for gzdoom -- it'll only be merged for compat if the feature lands on zandro

**Comment by RicardoLuis0** [comment]
just waiting on CI to run 👍

**Pull request merged**
