### PR TITLE
- add 'mapinfo' ccmd

### PR DESCRIPTION
**Pull request by madame-rachelle**
Mostly doing this in a PR because of uncertainty with the "testlocalised" function

### CODE REVIEW

**Comment by madame-rachelle** [comment]
Sample of how it works:
image

**Comment by madame-rachelle** [comment]
About the force-pushes - fixed a crash error, and also fixed a minor mistake.

**Comment by prof-hastig** [comment]
From looking at the source it needs to be different for different fields.

To get the level name, use the LookupLevelName function. This is quite a bit more complex from the looks of it.
For music you need to prepend "D_" if it is a language string. The strings this replaces and which are accessible by Dehacked do not contain "D_".

**Comment by coelckers** [comment]
Yeah, that part definitely needs fixing. The overall feature is fine but it needs to print the correct strings.
On that note, maybe print all available languages as an option? I know that needs a bit of work but would be cool.

**Comment by madame-rachelle** [comment]
Yeah Hastig's feedback is definitely good but it's not something that I will be able to address quickly. I just hope that I can get to it before this PR becomes stale.

**Comment by coelckers** [comment]
I'll merge it so that it's easier to work on. What's there may be a bit incomplete but it's not broken

**Pull request merged**
