### PR TITLE
Added SECMF_HURTMONSTERS, SECMF_HARMINAIR, and +NOSECTORDAMAGE.

### PR DESCRIPTION
**Pull request by inkoalawetrust**
This PR finally adds the ability to quickly make a sector able to harm monsters and other NPCs with the exact same behavior used on players. Without having to resort on functions like SectorDamage().

The PR also additionally includes SECMF_HARMINAIR, which replicates the behavior of SectorDamage()'s DAMAGE_IN_AIR flag. And also includes a new +NOSECTORDAMAGE flag, which makes actors with it immune to damaging floors and sectors entirely.

P_IsUnderDamage() has also been updated to be able to check if the sector the monster is on can harm it.

Also this PR does expose a few sector flag enums to ZScript that weren't exposed before as well.

### CODE REVIEW

**Comment by MajorCooke** [comment]
I think this could also benefit from +SECTORDAMAGE which allows for monsters to take sector damage. This would allow me to rid myself of a bunch of hacky implementations that I added in my minecraft mod.

I'd also like to suggest some form of check to see if a monster is in a position where they'll take sector damage.

**Comment by inkoalawetrust** [comment]
What do you mean a +SECTORDAMAGE flag? Sectors already have a SECMF_HURTMONSTERS flag that hurts monsters when enabled (If there is damage to the sector), the +NOSECTORDAMAGE is specifically for making monsters immune. Monsters will take damage by default if the sector has HURTMONSTERS.

As for checking if a monster is in a position where they'll take damage, I could expose P_IsUnderDamage() to ZScript (Which should also check for crushers too).

**Comment by MajorCooke** [comment]
I'm talking for specific monsters. I.e. my Triple M monsters have the ability to take damage, but I want it specifically on only a few monsters. That's why I'd like +SECTORDAMAGE.

**Comment by inkoalawetrust** [comment]
So would it work by having monsters/actors with the flag always be affected by sector damage even if it doesn't have SECMF_HURTMONSTERS?

**Comment by MajorCooke** [comment]
Yep. That's the idea. If it can damage the player, it can damage the monster with the flag too. I've had to insert a lot of hacks on my own end and it'd be nice to finally remove them.

**Comment by inkoalawetrust** [comment]
Alright, if any maintainer will be willing to merge it, then I'll add that flag before it's ready to be merged.

**Comment by FDinolfo** [comment]
This is actually something that would benefit the maps we're working on. If this could get merged soon, that would be great. Because it would absolutely be used. It's something we've wanted for a long time.

**Comment by MajorCooke** [comment]
> Alright, if any maintainer will be willing to merge it, then I'll add that flag before it's ready to be merged.

Don't wait, just do it. Otherwise, no one will want to merge it because they're waiting on you.

**Comment by inkoalawetrust** [comment]
Alright, I'll see about adding +FORCESECTORDAMAGE tomorrow or something then.

**Comment by MajorCooke** [comment]
> Alright, I'll see about adding +FORCESECTORDAMAGE tomorrow or something then.

Well, you'll now have to make a new PR for it

**Comment by inkoalawetrust** [comment]
Oops lol, tomorrow I guess. If I have time, too tired to do it now.

**Pull request merged**
