### PR TITLE
Particle Collision [WIP]

### PR DESCRIPTION
**Pull request by RicardoLuis0**
Floor collisions are implemented, but not tested 100%, and wall collisions aren't implemented at all

### CODE REVIEW

**Comment by mc776** [comment]
what does SPF_COLLIDE do?

**Comment by RicardoLuis0** [comment]
it enables particle collisions (SPF_STICK and SPF_BOUNCE also enable them, but with different behavior on impact)

**Comment by RicardoLuis0** [comment]
particles with collision enabled _will_ be more expensive than particles without them, especially if they cross sectors very fast (collision data is recalculated for every sector change)

**Comment by madame-rachelle** [comment]
That is exactly what I am worried about. Particles have always been a low-impact way to do special effects without spawning dozens of actors. That being said it makes it possible to spawn 10's of thousands of them without putting a meaningful impact against the computer running them - I worry that a PR like this, even with caching and the like, even when this is completely disabled and never used, will have an unacceptable impact against game performance.

**Comment by coelckers** [comment]
That may be true but the general knowledge is that particles are cheap so people will inevitably use this without much consideration for performance. But adding all these portal checks is surely not cheap at all when done for thousands of particles like snow would require.

I surely won't consider this for the upcoming 4.9 release

**Comment by RicardoLuis0** [comment]
All the portal checks were _already_ done by particles before, all i'm adding is collision

**Comment by RicardoLuis0** [comment]
I'll close the PR. For now this will be added to Disdain

**Pull request closed without merging**
