### PR TITLE
Easier MacOS Compilation w/Open AL

### PR DESCRIPTION
**Pull request by CandiceJoy**
Added frameworks CoreAudio and AudioUnit for OpenAL on Mac.

Signed-off-by: CandiceJoy <candice@candicejoy.com>

### CODE REVIEW

**Comment by alexey-lysiuk** [comment]
Sorry, but "Easier MacOS Compilation w/Open AL" is rather meaningless description.
What is the problem this change tries to solve? Is it linking with static OpenAL library?

**Comment by CandiceJoy** [comment]
> Sorry, but "Easier MacOS Compilation w/Open AL" is rather meaningless description.
> What is the problem this change tries to solve? Is it linking with static OpenAL library?

Getting it to link properly with OpenAL in general, yeah.  Invariably It picks up the built-in one which messes up in-game (doesn't produce sound), or tries to link against a different system one only, which invariably results in cmake being unable to find CoreAudio and UnitAudio and throwing a link-time error.  The brew one seems to work, but if you use vcpkg, it will always pick the vcpkg one or the built-in one, which means you have to tell cmake exactly where brew's OAL is.  This fixes that by making cmake recognise CoreAudio and UnitAudio regardless of which one it's linking to, meaning that whether you use the brew one, the vcpkg one, or compile your own, it'll link against it without you having to tell cmake where it is.

(Sorry, hope that's a clear enough explanation :P  If you think it might break something or somesuch, though, feel free to close it.  This was one of those "I got it working on my machine and thought GZDoom in general could benefit" but if not, no harm no foul <333)

**Comment by alexey-lysiuk** [comment]
OpenAL-Soft links with [more system frameworks](https://github.com/kcat/openal-soft/blob/d9d445772c50e53c12ab77d97cc5f3a76839d83a/CMakeLists.txt#L1086-L1119) than are added by this change. Also, the actual list of frameworks depends on CMake build options.
So, you change fixes the problem of particular package manager because other needed frameworks are pulled by some other dependencies (or even GZDoom itself).
I let someone else to judge about usefulness of this change.

**Comment by CandiceJoy** [comment]
I can add other frameworks too, it's no problem :)

**Comment by coelckers** [comment]
I cannot help you with this - you have to clear it yourselves.

**Pull request merged**
