### PR TITLE
Harmony: Fix Echidna's class name

### PR DESCRIPTION
**Pull request by edthebat**
Echidna's class name was not fixed when the Harmony DECORATE was fixed.
This is probably inconsequential, but if future Harmony updates are at all possible, it seems smarter to fix this now than later.

### CODE REVIEW

**Comment by coelckers** [comment]
Are there any Harmony mods? I doubt it but let's better double check.

**Comment by madame-rachelle** [comment]
Yeah I pointed this out when talking to Ed - honestly I don't think any exist. If there are any (that'd matter anyway) they'd have to be really really recent, maybe even recent enough that they'd still be actively developed.

The only ones that I think would matter would be crossover types (i.e. Samsara or such).

**Comment by edthebat** [comment]
I agree it is a valid concern, but I am not aware of any Harmony mods in all of the years since it came out, least of all ones that with a class inheriting from Echidna ("Echida").

**Comment by madame-rachelle** [comment]
This should be safe to merge.

https://forum.zdoom.org/search.php?keywords=harmony&terms=all&author=&fid%5B%5D=41&sc=1&sf=firstpost&sr=topics&sk=t&sd=d&st=0&ch=300&t=0&submit=Search

The only mods that currently exist for Harmony, specifically, that don't accidentally mention the project by name synonymously, are HUD and widescreen graphic mods, at least that is on the ZDoom forum. I don't know how to do the same kind of search on Doomworld but I doubt there's anything there, either.

**Pull request merged**
