### PR TITLE
Fixed all of the for loops.

### PR DESCRIPTION
**Pull request by StrafeStopper**
Look guys, for loops are supposed to be made with the letter "i". It is just not good development practice to use any other letters, especially "j". And when you are using nested for loops, you can use the letter "i" twice, "ii". 

Long story short, I have corrected all of your for loops. You are welcome. 

If you would like me to help contribute anything else in the future, I would be happy to.

### CODE REVIEW

**Comment by OpticFusion1** [comment]
Fuck, guess the documentation on cplusplus.com needs changed https://cplusplus.com/doc/tutorial/control/. They're using "n"

**Comment by StrafeStopper** [comment]
Who on earth uses "n"? I'll get this sorted.

**Comment by OpticFusion1** [comment]
b
https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/Marlin/src/core/types.h#L249
https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/Marlin/src/core/types.h#L257

j
https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/Marlin/src/feature/bedlevel/abl/bbl.cpp#L235

f
https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/Marlin/src/feature/fancheck.cpp#L75

s
https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/Marlin/src/feature/fancheck.cpp#L179

being just some non "i" uses.

**Comment by StrafeStopper** [comment]
Looks like I have more work to do.

**Comment by OpticFusion1** [comment]
Better make a PR on the linux repo too, while you're at it.
https://github.com/torvalds/linux/blob/master/net/netfilter/ipset/ip_set_hash_gen.h#L332
https://github.com/torvalds/linux/blob/master/net/netfilter/ipset/ip_set_hash_gen.h#L364
https://github.com/torvalds/linux/blob/master/net/netfilter/ipset/ip_set_hash_gen.h#L405
https://github.com/torvalds/linux/blob/master/net/netfilter/ipset/ip_set_hash_gen.h#L501
https://github.com/torvalds/linux/blob/master/net/netfilter/ipset/ip_set_hash_gen.h#L688

**Comment by StrafeStopper** [comment]
Damn, I'm gonna be real busy cleaning github up.

**Pull request closed without merging**
