### PR TITLE
Isometric mode with orthographic projection (HW renderer only, 2nd attempt)

### PR DESCRIPTION
**Pull request by dileepvr**
Started with current state of master branch of GZDoom this time.
Copy-paste description from previous attempt:

All changes kick in conditional on a new boolean CVar called '`r_isocam`'. So traditional usage is unaffected. Tested with a basic multiplayer single-room wad as well.

Demo video: https://www.youtube.com/watch?v=mUt8Z8mkI-g

Test iwad (ipk3) and pwads: https://www.mediafire.com/file/klzfix9ubtqgtgy/gzdoom_isometric_wads.zip/file

The changes in a nutshell:

1. `VSMatrix VREyeInfo::GetProjection()` function in `src/common/rendering/hwrenderer/data/hw_vrmodes.cpp` now uses an extra boolean argument, and uses orthographic instead of perspective projection matrix based on the boolean.
2. The CVars '`r_isocam`', '`r_isoviewpoint`', '`r_iso_camdist`', '`r_iso_dist`', '`r_iso_pitch`', and '`r_orthographic`' were added to `src/common/rendering/hwrenderer/data/hw_cvars.h` and `src/rendering/r_utility.cpp`.
3. Added two integer variables ('`isoviewpoint`' and '`isoyaw`') to `playerpawn` class and made them usable from zscript.
4. Added an if-else block in `sector* RenderViewpoint()` function in `src/rendering/hwrenderer/hw_entrypoint.cpp` to change the projection matrix and move the camera position and view direction if the new CVar '`r_isocam`' is true.
5. Conditional if ('`r_isocam`') changes to `src/rendering/hwrenderer/scene/hw_sprites.cpp` :
    - Caused sprites to change pitch about their bottom-z instead of their z-center when not y-billboarding inside `bool HWSprite::CalculateVertices()`.
    - Face Sprite rotation uses just the camera's yaw inside `void HWSprite::Process()`.
    - Face Sprite gets displaced to front of collision box (from camera's perspective) in xy-plane instead of being at the center to help with sprites drawn from an isometric perspective. This is also inside `void HWSprite::Process()`.
    - Added a z-bottom ('`z2`') component to the sprite's '`depth`' variable, changing the weight based on camera's pitch to help render actors stacked on top of each other in the right order. Also inside `void HWSprite::Process()`.

### CODE REVIEW

**Comment by MajorCooke** [comment]
Now comes the time when isometric view should be controllable by the modder in particular, instead of through console cvars. Easiest thing I could think of is via the `player` struct that can be adjusted via ZScript.

**Comment by dileepvr** [comment]
The two integers `isoviewpoint` and `isoyaw` are part of PlayerInfo struct (player_t class), and are being used to rotate the camera yaw in the example iwad. Do you think even pitch and the very isometric mode need to be controllable that way?

**Comment by MajorCooke** [comment]
Pitch, definitely. I'll have to test out the rest soon.

**Comment by dileepvr** [comment]
Some changes made as requested:

1. New mapinfo variables '`isometricmode`', '`orthographic`', '`isometricsprites`', '`isocam_pitch`', and '`iso_dist`' now let modders control without using CVars.
2. PlayerInfo struct had the '`isoviewpoint`' variable removed, as '`isoyaw`' us enough.
3. CVars still work (since this was considered useful for testing). The CVar '`r_isoviewpoint`' has a slight functionality change.
4. Minor improvement. Some trig functions now execute once per renderview instead of once for every sprite.
5. Demo iwad and pwads updated (same link).

**Comment by madame-rachelle** [comment]
It sucks I had to do this but I had to revert this PR :( With the other one I merged it was causing compile errors, apparently too many things changed with the first one that caused this one to stop working. I'll see if I can fix this on my own later on ...

**Comment by dileepvr** [comment]
Replacing `zcenter` with `center.Z` in two of my line additions to `hw_sprites.cpp` does the trick.

**Comment by MajorCooke** [comment]
The only thing to be done now is make another PR. Sorry for the trouble. :(

**Pull request merged**
