### PR TITLE
Update to use the new ZMusic_GetStreamInfoEx

### PR DESCRIPTION
**Pull request by kcat**
This doesn't seem to want to build on CI currently, as its using the internal ZMusic files in `bin/windows/zmusic`. I can't update the Windows binaries (the import `.lib` files I could make have had issues with MSVC before, and for some reason there's a DLL in there for arm64?), so someone else will need to update that stuff before this can be merged.

Once that's updated, this is merged, and I can start adding support for surround sound formats to ZMusic without GZDoom breaking, which will then allow surround sound support to be added to GZDoom.

### CODE REVIEW

**Review by alexey-lysiuk — COMMENTED** [review]
We need a new ZMusic release, 1.1.9 or even 1.2.0. After that, updating CI and Windows header/.libs is a trivial task.

**Comment by CandiceJoy** [comment]
This is still open; do you have any interest in continuing with this PR?  @kcat

**Comment by kcat** [comment]
I do. I'll look into getting the conflicts resolved sometime within a couple days.

**Comment by kcat** [comment]
Is there a way to push from a different branch to here instead of from master, or does this need to be closed and a new one made?

**Comment by madame-rachelle** [comment]
Yes you can edit the pull request and there is a drop down which lets you specify which branch to merge to.
image

**Comment by kcat** [comment]
I mean to change the source branch, `kcat:master`, not which branch to merge this into.

**Comment by kcat** [comment]
Hmm, well I can't see how to, so I'll just make a new one.

**Pull request closed without merging**
