### PR TITLE
Mingw64 fixes

### PR DESCRIPTION
**Pull request by Ritchie333**
I had problems compiling GZDoom on the latest release of MSYS / Mingw64 on Windows 11, so I've done a branch with fixes. I've done a basic "smoke test" of starting the game up and going through E1M1 on normal skill level, but nothing else.

Most of these should be fairly uncontroversial, the two that I think need closer review are the library changes in CMakeList.txt (to stop linker errors) and the commenting out of DwmDefWindowProc (which also generates a linker error if left in).

### CODE REVIEW

**Comment by Ritchie333** [comment]
I've done a better fix for the DwmDefWindowProc linker error on mingw64, which uses a late-binding fix. I prefer this as it doesn't get compiled on any other architecture or toolchain, so the impact is minimal.

**Comment by coelckers** [comment]
Why was this merged? It contains a lot of deprecated tchar.h related stuff that serves no purpose aside from making the source unstable.

**Comment by Ritchie333** [comment]
I've never seen a reference describing TCHAR as deprecated, and I would be interested in seeing examples of how it makes the source unstable, particularly as the automated build tests passed correctly. As far as I can tell, the only thing using this are Windows-specific implementations using hard-coded filenames.

As mentioned above, the principal reason for this that I took a fresh installation of MinGW and, testing it out, decided to compile GZDoom on it, and got compile and link errors. Rather than raising an issue here or just complaining "it doesn't work", I thought I'd be a bit more pro-active and fix them. I think this subscribes to the project's overall ethos that you should be able to compile GZDoom on whatever platform, architecture and toolset you wish, provided it does not regress any of the others.

**Comment by coelckers** [comment]
In that case better fix the issues for real. tchar.h is pointless because its only purpose is to conditionally compile as ANSI which GZDoom doesn't even support anymore because it depends on Unicode. UNICODE and _UNICODE *must* be defined or you will get undefined behavior somewhere.

**Comment by Ritchie333** [comment]
Okay, understood. It turns out forcing MinGW to do a unicode build is straightforward.

As this pull request has been closed, I'll send a new one with that fix.

**Pull request merged**
