### PR TITLE
Add an option to only build the tools

### PR DESCRIPTION
**Pull request by glebm**
This is useful when cross-compiling.
Rather than building all of gzdoom for host, only configure and build the CROSS_EXPORTS tools.

### CODE REVIEW

**Comment by glebm** [comment]
@alexey-lysiuk That does not work because it fails the configure stage.
At the configure stage, dependencies of all the targets must be present.

**Comment by glebm** [comment]
> What doesn't work exactly? What does fail configure stage?

All the many gzdoom dependencies. We don't want to install all these unused dependencies them into sysroot for no reason.

**Comment by glebm** [comment]
> You don't need to install anything from host/native build when cross-compiling

We do need the tools, precisely the ones exported by `CROSS_EXPORTS`, for example `zipdir`.

**Comment by madame-rachelle** [comment]
CMake is due for a revamp and is deprecated in its current form; this cannot be accepted at this time.

**Comment by glebm** [comment]
This is a trivial bug fix to an obvious mistake.

I guess this explains why gzdoom isn't in a whole lot of Linux distributions.

**Comment by coelckers** [comment]
For a 'trivial' bug fix this is doing a lot of code changes. The project file has become the monstrosity it is because too many people felt they had to add some 'trivial' additions to it that maybe served them but not the project.

**Comment by glebm** [comment]
Oh, I responded to the wrong PR.
The trivial one is this one: https://github.com/ZDoom/gzdoom/pull/1795

**Pull request closed without merging**
