### PR TITLE
Zscript Custom CVars

### PR DESCRIPTION
**Pull request by RicardoLuis0**
Allows a ZScript handler to constrain or observe changes to a CVar.
Example: [CustomCVarTest.zip](https://github.com/ZDoom/gzdoom/files/10251919/CustomCVarTest.zip)

Due to the way User CVars are currently implemented, it was infeasible to handle changes to them outside of the Console -- should they be overhauled in the future, it might be possible to add support for them outside of the console as well.

### CODE REVIEW

**Comment by CandiceJoy** [comment]
I'm using the provided test mod in a clean QZDoom, aside from my ini.  If you notice, float doesn't seem to want to change correctly and colour won't go past c0

image
image

**Comment by RicardoLuis0** [comment]
>  float doesn't seem to want to change correctly and colour won't go past c0

that's intended behavior, the int cvar clamps it to a positive value, the float cvar clamps it between 1 and -1, the string cvar strips left whitespace, and the color cvar clamps each r/g/b value between 0x40 (64) and 0xC0 (192)

**Comment by CandiceJoy** [comment]
Ooooooookkkkkkk thennnnnnnnn

**Comment by RicardoLuis0** [comment]
> it's very random ;)

yeah, it's intended to show that you can use this to constrain cvars to allowed ranges, ex. if a negative cvar value would cause issues, you just don't let it be changed to a negative value. (i still think i'll give this PR a look again soon, to see if i can't implement it for user cvar changes from zscript as well)

**Comment by CandiceJoy** [comment]
Yep okay looks good :)

**Pull request merged**
