### PR TITLE
Add a cvar to control camera bob factor

### PR DESCRIPTION
**Pull request by Calinou**
This allows disabling camera bobbing without disabling weapon sprite bobbing. The landing camera effect is not affected by this cvar.

This is a multiplier, which means 1.0 is the original behavior and 0.0 fully disables camera bobbing (including `stillbob`, but not fly bobbing, which is controlled by the `fviewbob` boolean cvar).

This partially addresses https://github.com/ZDoom/gzdoom/issues/1934.

## Preview

Using the following settings:

```c
camerabob 0.0  // disables camera bobbing
movebob 0.015  // strongly decreased to better mesh with the doubled weapon bob speed from this example
stillbob 0.0   // default
wbobspeed 2.0  // doubled from default
wbobfire 1.0   // keeps full weapon bobbing while firing
```

https://user-images.githubusercontent.com/180032/212574028-dd3b3ac0-1a0e-4fec-990a-3c00705da7d5.mp4

### CODE REVIEW

**Comment by RicardoLuis0** [comment]
this doesn't feel like the right approach to me, IMO instead of adding a multiplier for view bob, the best would be to decouple the movebob/stillbob CVARs from weapon bob entirely, with moveweaponbob/stillweaponbob cvars for weapon bobbing

**Comment by MajorCooke** [comment]
I'll hold off merging this into QZDoom until a dev can review the code first.

**Comment by CandiceJoy** [comment]
> this doesn't feel like the right approach to me, IMO instead of adding a multiplier for view bob, the better option would be to decouple the `movebob`/`stillbob` CVARs from weapon bob entirely, with a separate `weaponbob` CVAR for weapon bobbing

I tend to agree with this. It feels more like a bandaid than a true fix. But that’s just my 2 cents ^_^

**Comment by RicardoLuis0** [comment]
reiterating:

> instead of adding a multiplier for view bob, the better option would be to decouple the `movebob`/`stillbob` CVARs from weapon bob entirely, with a separate `weaponbob` CVAR for weapon bobbing

**Pull request closed without merging**
