### PR TITLE
Isometric mode with orthographic projection (hardware renderer only)

### PR DESCRIPTION
**Pull request by dileepvr**
All changes kick in conditional on a new boolean CVar called 'r_isocam'. So traditional usage is unaffected. Tested with a basic multiplayer single-room wad as well.

Demo video: https://www.youtube.com/watch?v=mUt8Z8mkI-g

Test iwad (ipk3) and pwads: https://www.mediafire.com/file/klzfix9ubtqgtgy/gzdoom_isometric_wads.zip/file

The changes in a nutshell:

1. `VSMatrix VREyeInfo::GetProjection()` function in `src/common/rendering/hwrenderer/data/hw_vrmodes.cpp` now uses an extra boolean argument, and uses orthographic instead of perspective projection matrix based on the boolean.
2. The CVars '`r_isocam`', '`r_isoviewpoint`', '`r_iso_camdist`', '`r_iso_dist`', '`r_iso_pitch`', '`r_drawplayersprites`', and '`r_orthographic`' were added to `src/common/rendering/hwrenderer/data/hw_cvars.h` and `src/rendering/r_utility.cpp`.
3. Added two integer variables ('`isoviewpoint`' and '`isoyaw`') to `playerpawn` class and made them usable from zscript.
4. Added an if-else block in `sector* RenderViewpoint()` function in `src/rendering/hwrenderer/hw_entrypoint.cpp` to change the projection matrix and move the camera position and view direction if the new CVar '`r_isocam`' is true.
5. Conditional `if ('r_isocam')` changes to `src/rendering/hwrenderer/scene/hw_sprites.cpp` : 
    - Caused sprites to change pitch about their bottom-z instead of their z-center when not y-billboarding  inside `bool HWSprite::CalculateVertices()`.
    - Face Sprite rotation uses just the camera's yaw inside `void HWSprite::Process()`.
    - Face Sprite gets displaced to front of collision box (from camera's perspective) in xy-plane instead of being at the center to help with sprites drawn from an isometric perspective. This is also inside `void HWSprite::Process()`.
    - Added a z-bottom ('`z2`') component to the sprite's 'depth' variable, changing the weight based on camera's pitch to help render actors stacked on top of each other in the right order. Also inside `void HWSprite::Process()`.

### CODE REVIEW

**Comment by RicardoLuis0** [comment]
also, this seems like it would be better as a mapinfo flag, rather than a cvar

**Comment by RicardoLuis0** [comment]
(also, you shouldn't develop on release tags -- they have extra commits -- ex. g4.11.3 is a patch to 4.11 with backported commits from 4.12 -- to fix this, you can cherry pick your commit to a branch based on master)

**Comment by coelckers** [comment]
The feature is cool, but this PR is not usable due to being based on an outdated release branch.
There's also another few problems here, like cosmetic changes in unrelated files or unrelated parts of files.
Please resubmit this in a clean fashion as a new PR, this one isn't salvageable due to the problems that have been pointed out.

**Comment by nashmuhandes** [comment]
As I've said on the Youtube video, looking awesome!

- Echoing what others have said here, but putting extra emphasis on what Ricardo said - IMO this feature should really be a feature of the camera actor itself (additional properties on them) -- not sure if I agree that MAPINFO is necessary (but maybe @RicardoLuis0 could elaborate further on the MAPINFO aspect)


- I have an additional suggestion. In Diablo II Resurrected (the remastered version) there is an option that enables a very tiny hint of perspective (called perspective mode under the Legacy options). Would this be possible to add too? There's only this video to demonstrate it and while it may be quite subtle, it's definitely there and does add a small touch of atmosphere.


https://www.youtube.com/watch?v=QK5bGcMSKvY

**Comment by dileepvr** [comment]
Okay. I'll fix the extra useless changes to unrelated files and work with the master branch from the current state and retry.
Thank you for the comments.
I had a question about the camera options. I am placing the camera position at a constant offset from player. So since I am not working with a camera "actor" I am not restricted to be within a map sector. Would this be possible through "camera options"? I probably don't understand. Maybe what I'm doing is bad practice.

**Comment by MajorCooke** [comment]
For right now I suggest just getting the PR up and going, and then we can deliberate further. Alternatively, we can also discuss this more on the Discord server, link in the ZDoom forums.

**Comment by madame-rachelle** [comment]
>     * I have an additional suggestion. In Diablo II Resurrected (the remastered version) there is an option that enables a very tiny hint of perspective (called perspective mode under the Legacy options). Would this be possible to add too? There's only this video to demonstrate it and while it may be quite subtle, it's definitely there and does add a small touch of atmosphere. Perhaps this could be exposed as a "perspective factor" `double` value to control the amount of perspective.
> 
> 
> Video demo of the perspective effect on an isometric camera: https://www.youtube.com/watch?v=QK5bGcMSKvY
@nashmuhandes 
For this you don't need isometric view at all. Simply pull the camera out very far and set it to a narrow FOV. The narrow FOV still allows a perspective shift, but with the considerable distance it is still a lot less than the traditional camera. In fact, to emulate Diablo II's perspective view, you don't even really need to pull it out that far. An FOV of 35 would probably be quite sufficient.

**Comment by RicardoLuis0** [comment]
> Okay. I'll fix the extra useless changes to unrelated files and work with the master branch from the current state and retry. Thank you for the comments. I had a question about the camera options. I am placing the camera position at a constant offset from player. So since I am not working with a camera "actor" I am not restricted to be within a map sector. Would this be possible through "camera options"? I probably don't understand. Maybe what I'm doing is bad practice.

you'd place the isometric camera the same way, but using the camera actor's position instead of the player's position

**Comment by MajorCooke** [comment]
I would still prefer there being an actual isometric view regardless. It'll help with a few projects I'm working on.

**Comment by RicardoLuis0** [comment]
> > ```
> > * I have an additional suggestion. In Diablo II Resurrected (the remastered version) there is an option that enables a very tiny hint of perspective (called perspective mode under the Legacy options). Would this be possible to add too? There's only this video to demonstrate it and while it may be quite subtle, it's definitely there and does add a small touch of atmosphere. Perhaps this could be exposed as a "perspective factor" `double` value to control the amount of perspective.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Video demo of the perspective effect on an isometric camera: https://www.youtube.com/watch?v=QK5bGcMSKvY
> 
> @nashmuhandes For this you don't need isometric view at all. Simply pull the camera out very far and set it to a narrow FOV. The narrow FOV still allows a perspective shift, but with the considerable distance it is still a lot less than the traditional camera. In fact, to emulate Diablo II's perspective view, you don't even really need to pull it out that far. An FOV of 35 would probably be quite sufficient.

that wouldn't work using just a camera actor in gzdoom unfortunately, since actors can't go above the ceiling

**Comment by coelckers** [comment]
Guys, please refrain from discussing these things now. As a first step we need the feature in with a CVAR as controlling entity so that we can test it without fighting against setup methods.
The rest can be done once it has been tested and been confirmed to be working.

**Pull request closed without merging**
