### PR TITLE
Switch to miniz from zlib

### PR DESCRIPTION
**Pull request by Cacodemon345**
This PR replaces zlib with miniz.

The miniz library is smaller and much more cleaner than zlib.

### CODE REVIEW

**Review by alexey-lysiuk — COMMENTED** [review]
I have no idea about quality and performance of miniz, but this change makes usage of other zlib implementations (like zlib-ng) impossible.

**Comment by coelckers** [comment]
Most other ports use miniz as well. Its biggest advantage is that it is far more compact than zlib - not even zlib-ng goes the full route to make it compact.

That said, what's with the CRC table in models.cpp? That's plain and simply unacceptable and needs to go away.

**Comment by Cacodemon345** [comment]
miniz for some unknown reason doesn't implement the officially-undocumented function `get_crc_table` that is used for hashing in the model code, although it does have it internally in the library code for the `crc32` implementation.

I can upstream a PR to miniz to implement it and custom-patch the code on our side to make the table available via it to keep the code clean.

**Comment by coelckers** [comment]
There's absolutely no need for that.
Either pass the memory block as a whole to the CRC function or use superfasthash.
The hash is only needed for a hash table and not exposed to the user in any way.

**Comment by Cacodemon345** [comment]
@coelckers Done as requested.

**Comment by coelckers** [comment]
Merged manually

**Pull request closed without merging**
