### PR TITLE
Add support for fire textures in ANIMDEFS

### PR DESCRIPTION
**Pull request by Cacodemon345**
This PR adds support for defining fire textures in ANIMDEFS.

Syntax is:
FIRETEXTURE tics <numtics>

followed by a series of either "palette index" or "color red green blue alpha".

Example (converted from Legacy of Rust's SKYDEFS definition):
```
firetexture FIRETEST tics 2.00025
	palette 0
	palette 47
	palette 191
	palette 187
	palette 235
	palette 234
	palette 232
	palette 167
	palette 166
	palette 165
	palette 223
	palette 221
	palette 220
	palette 219
	palette 217
	palette 216
	palette 215
	palette 214
	palette 213
	palette 164
	palette 163
	palette 162
	palette 161
	palette 160
	palette 231
	palette 230
	palette 229
	palette 228
	palette 227
	palette 226
	palette 225
	palette 224
```

### CODE REVIEW

**Comment by coelckers** [comment]
Please make this work in the software renderer as well.

**Review by coelckers — CHANGES_REQUESTED** [review]
Please make this work in the software renderer as well.

**Comment by Cacodemon345** [comment]
Is implementing `Get8BitPixels` enough for the software renderer? If so, it has been done now.

**Comment by prof-hastig** [comment]
Why don't you just test it?
Enabling both modes of the software renderer is not that hard...

**Comment by Cacodemon345** [comment]
It only works with the hardware renderer and the non-truecolor software renderer. On truecolor software renderer it remains frozen.

**Comment by prof-hastig** [comment]
My suggestion here would be to look how warped flats force their update and replicate it for this texture.

**Comment by Cacodemon345** [comment]
Fixed for truecolor software renderer.

**Comment by Cacodemon345** [comment]
As an addendum: Specifying the first color with the `color` syntax with the alpha part maxed out (`color 0 0 0 255`) should disable transparency.

**Comment by coelckers** [comment]
It may be a bug in the true color software renderer, but I don't really know how to address it.

**Comment by Cacodemon345** [comment]
Does this happen with the sky or just linedefs? At least I could attempt fixing the truecolor sky renderer but I'm not sure about anything else.

**Comment by Cacodemon345** [comment]
It happens with the sky, not linedefs. I have no idea why it happens; the sky drawer code's not easy to read.

**Comment by Cacodemon345** [comment]
Defining an opaque black color as the first one indeed deals with the HOM problem.

**Comment by Cacodemon345** [comment]
The HOM problem should be addressed now.

**Comment by coelckers** [comment]
Seems to work now

**Pull request merged**
