### PR TITLE
Weapon.Raise/Lower/LiftSpeed properties

### PR DESCRIPTION
**Pull request by MajorCooke**
Added Raise/LowerSpeed properties to weapons, allowing for control outside of A_Raise/Lower.

- Weapon.LiftSpeed can set them both at once.

### CODE REVIEW

**Comment by RicardoLuis0** [comment]
is there any actual need for this? you can just pass a const directly to A_Raise/A_Lower instead, this just adds unnecessary complexity

**Comment by MajorCooke** [comment]
I've an upgrade system that's meant to be compatible with other mods. Mods outside the mod cannot be modified directly.

**Comment by RicardoLuis0** [comment]
if you need to speed up the raise/lowering of another mod, you can directly modify the offset

**Comment by MajorCooke** [comment]
No. This is a much safer way to do this.

**Comment by RicardoLuis0** [comment]
i can assure you it is not

**Comment by RicardoLuis0** [comment]
this wouldn't even work if the mod passes a speed directly to A_Raise/A_Lower, and wouldn't work at all with animation-based raise/lower animations, no need to add ugly hacks to the engine for a half-solution

**Comment by Boondorl** [comment]
Yeah, gonna have to reject this one as well. Not only does the solution fail if someone uses a custom A_Raise/Lower speed (the proper way to handle this), but this is taking universal mods too far IMO. The are other ways that can tackle this that, while imperfect, have no more imperfections than this solution anyway. And as Ricardo pointed out, this doesn't capture the case at all where someone uses an animation and avoids offsetting directly. Offsets themselves could already be seen as a bit of a hack from a modern perspective compared to using a timer proper, so I think it'll have to be accepted that there simply can't be a universal solution, only one that captures the most common use cases. That solution doesn't require modifying the engine.

**Pull request closed without merging**
