### PR TITLE
Add Textured Particles

### PR DESCRIPTION
**Pull request by RicardoLuis0**
Allows creation of particles with custom textures and render styles.
image
[particle_texture_test.zip](https://github.com/ZDoom/gzdoom/files/9913447/particle_texture_test.zip)

### CODE REVIEW

**Comment by MajorCooke** [comment]
While we're at it... Can we do something about the limit system? In particular, the way the engine is set up, particles will not spawn unless there's enough space. 

Can we have an option to change it so particles can override and destroy the oldest particles if the limit is reached?

**Comment by RicardoLuis0** [comment]
I don't know enough about the particle system to change that for now, this was possible because the particle rendering already handles render styles/textures/etc and it only needed to add fields in the particle info for them, and glue to pass that info from ZS to the particle system

**Comment by coelckers** [comment]
The thing with the particle system is that it operates on a static array for performance reasons. More flexibility here may easily result in worse performance.

**Comment by MajorCooke** [comment]
That's why I would make it an opt-in flag. Otherwise, it would just be spawned normally.

**Pull request merged**
