### PR TITLE
[WIP] ZSprites

### PR DESCRIPTION
**Pull request by MajorCooke**
ZSprites is a dedicated system to rendering actor sprites without all the baggage actors carry.

### CODE REVIEW

**Comment by MajorCooke** [comment]
While I'm working on states, I would like to discuss how to set this up for rendering. Several I can think of...

The only thing I can think of is to make a(n) HWZSprite class with similar rendering mechanics as HWSprite, but stripped down to the bare minimum needed. No model processing, no FLAT/WALL sprite handling, and greatly sectioned off with simple checks included.

Particles will not do, because that would mean expanding the particle system for Actor's SpriteOffset, etc. 

Any other ideas?

**Comment by Talon1024** [comment]
Is this a feature which will allow sprites to be made dynamically with ZScript, like [N00b's patchwork enemies](https://forum.zdoom.org/viewtopic.php?p=1245304)?

**Comment by RicardoLuis0** [comment]
> Is this a feature which will allow sprites to be made dynamically with ZScript, like N00b's patchwork enemies?

No, it's a for allowing a lighter type of actor, basically, particles++

**Comment by MajorCooke** [comment]
What you CAN do is utilize the texture to display whatever graphic you want.

**Comment by Talon1024** [comment]
ZSprites are particles with state sequences? Interesting. I still have a few questions, however:

1. Will we be able to make ZSprites 3D models, wallsprites, or flatsprites?
2. Will it be possible to run through a certain state sequence when or before a ZSprite lifetime ends?
3. Will ZSprites or particles use instancing?

**Comment by MajorCooke** [comment]
> ZSprites are particles with state sequences? 
States are on hold because I hadn't realized how thoroughly involved that whole system is so it'd take a lot more time than I thought.
> I still have a few questions, however:
> 1. Will we be able to make ZSprites 3D models, wallsprites, or flatsprites?
No. Also, consider flatsprites deprecated. Use a 3D model for that instead so it has proper rotations.
> 2. Will it be possible to run through a certain state sequence when or before a ZSprite lifetime ends?
Unknown.
> 3. Will ZSprites or particles use instancing?
Can you clarify more in depth?

**Comment by Talon1024** [comment]
> > 3. Will ZSprites or particles use instancing?
> 
> Can you clarify more in depth?

Objects can be rendered with individual draw calls, or they can be rendered with one instanced draw call. [There's a lot more info about instancing here](https://learnopengl.com/Advanced-OpenGL/Instancing).

**Comment by MajorCooke** [comment]
I've had suggested to me to make a a class with an array of properties that pertain to particles, which should be faster to traverse than making an HWSprite every time a particle is made. So I intend to test that with ZSprites and particles. 

Aside from that, the only other thing I can think of would be to make a theoretical alternative to `HWSprite` that trims all the fat and keep only what is related to it.

I'm really not all that good with anything beyond that...

**Comment by MajorCooke** [comment]
Closing this and opening up a cleaner PR.

**Pull request closed without merging**
