### PR TITLE
Change `CheckValue` to multi-return, due to unsupported out int/bool

### PR DESCRIPTION
**Pull request by RicardoLuis0**
The VM doesn't support out int/bool parameters for native functions

### CODE REVIEW

**Comment by coelckers** [comment]
A better solution would be to change the return value of these functions. Especially for such basic functions we should avoid function call overhead.

**Comment by CandiceJoy** [comment]
I agree with Graf.  The additional overhead from a function call for something like CheckValue, especially, isn't worth it.

**Comment by RicardoLuis0** [comment]
is a multi-return possible from a native function? this function _needs_ to return both values, for either value separately there's `GetIfExists` and `CheckKey`

**Comment by RicardoLuis0** [comment]
Changed it to a multi-return function instead, new example:
[MapNewFnsMultiReturnsTest.zip](https://github.com/ZDoom/gzdoom/files/10501180/MapNewFnsMultiReturnsTest.zip)

**Pull request merged**
