### PR TITLE
Add scrollbar for Linux IWAD Selection.

### PR DESCRIPTION
**Pull request by Radon86222**
To fulfill #1451. Please review carefully. Have not tested this with a GTK2-only system yet. Note that this currently sets height to screen height / 2, which may need to be adjusted for stylistic purposes (it could look ridiculous on massive displays). This also technically enables horizontal scrolling (why not!).

### CODE REVIEW

**Review by alexey-lysiuk — CHANGES_REQUESTED** [review]
It doesn't compile with GTK 2.

**Comment by Radon86222** [comment]
Removed GDK use and resolution scaling, it caused more problems than it was worth. Should now compile on GTK2 (hopefully?). Current window sizes tries to show ~6 IWAD choices, at a fixed size of 280 pixels in height.

**Comment by mjr4077au** [comment]
Just my two cents, but is GTK 2 as a target even worth our time anymore? Its over two decades old, even GTK 3 is a decade old...

**Comment by Radon86222** [comment]
I was also thinking that, but I'm just assuming they have their reasons.

**Comment by alexey-lysiuk** [comment]
It still doesn't compile.

Regarding removal of GTK2, I'm fine with it. I would like to hear others' options on this. You can prepare a separate pull request if you want, and we discuss it there.

**Comment by madame-rachelle** [comment]
GTK dialog is redone in this commit: https://github.com/ZDoom/gzdoom/commit/7ae07d614eba7fefe3505d798a0004d65ddfdbba

If there are any problems with it still, please create a new pull request.

**Pull request closed without merging**
