### PR TITLE
Update README.md for a more simple and compact approach

### PR DESCRIPTION
**Pull request by Degamisu**
This is just some small improvements to your readme! Hope you like it.

### CODE REVIEW

**Comment by mc776** [comment]
This just hides the URLs from the reader until they mouseover, doesn't it?

**Comment by Degamisu** [comment]
> This just hides the URLs from the reader until they mouseover, doesn't it?

Yes.

**Comment by coelckers** [comment]
That's not user friendly.

**Comment by madame-rachelle** [comment]
I'm going to have to agree. When I made this readme file I had already known about markdown links and could have already used them, but I didn't. There likely would have been a reason for that other than the inconvenience of having to remember in what order which marks go.

Besides this readme isn't made for giving a good first impression, it's made to give information, first and foremost. It describes what the project is, and various links on how to get documentation as well as how to get in touch with the developers and connect with the community. Also I made it because Github was nagging me that the project had no readme file every time I opened the page.

**Pull request closed without merging**
