### PR TITLE
Switch to `vcpkg` for library dependencies

### PR DESCRIPTION
**Pull request by Cacodemon345**
This PR switches to Microsoft's `vcpkg` for library dependencies.

### CODE REVIEW

**Review by alexey-lysiuk — COMMENTED** [review]
I'm strictly against **mandatory** usage of any package manager. Even on Windows this is not the best solution, on Linux/macOS it's pure bullshit. Optional support of vcpkg would be fine.

**Comment by prof-hastig** [comment]
Regardless of what you decide here, OpenAL should not be pulled from vcpkg. There's good reasons to keep this as an external DLL, same for libsndfile.

What would be nice is to have vcpkg configured to pull and configure all unknown dependencies. That would make it a lot easier to add new ones without having to provide the source, just to be able to compile on Windows. The user should still have the option to provide their own ones, of course.

**Comment by Cacodemon345** [comment]
vcpkg's CMake toolchain file has no function to download dependencies on-demand at all; it all has to be done at `project` command invocation.

**Comment by coelckers** [comment]
What that mean in clear English?

**Comment by coelckers** [comment]
I think this is ready to merge, but I'd like to hear from others, what they thing especially @alexey-lysiuk about the voiced reservations. This really is the only way forward for adding features requiring more complex dependencies, like modern image and video formats like WebP or WebM.

**Comment by alexey-lysiuk** [comment]
As long as possibility to build without `vcpkg` remains, I'm fine with it. Please squash all commits into one when merging.

**Comment by coelckers** [comment]
On Linux and macOS it should of course be able to use the system provided libraries - or your own maintained package, that is. But we all know that on Windows there really is no better option to pull in larger dependencies. Doing it manually is simply not feasible because several do not come with sane project setups or easy to use downloads.

I surely wouldn't block a Windows user from doing it, but it's a very bumpy road...

**Pull request merged**
