### PR TITLE
Move no-mipmapping from actor renderflag/particle flag, to a material…

### PR DESCRIPTION
**Pull request by nashmuhandes**
… property in GLDEFS, where it makes more sense. The feature was introduced in the short-lived engine version of 4.13 which was deemed too broken and needed to be replaced with a newer version anyway, so might as well perform an API-breaking change at this point in time. Note that this currently only works for sprites (its primary targeted use case) -- walls, flats and models can be patched in later.

To re-iterate its use case - small, moving transparent sprites look undesirable with mipmapping (can be seen in the example file) -- they "phase" in and out with camera distance.

Example file: 

[NoMipmapTest2.zip](https://github.com/user-attachments/files/17436323/NoMipmapTest2.zip)

### CODE REVIEW

**Comment by madame-rachelle** [comment]
I would like an opinion from @coelckers before moving forward with this one. GZDoom has historically been an engine that generally respected backwards compatibility but this truly has never been 100% the case, there have been exceptions here and there (Doomsday hi-res textures being probably the most prominent). Sometimes it does make sense to break with that norm, but I don't have a dog in this fight, other than to say I have no issue with whatever the final decision will be.

**Comment by nashmuhandes** [comment]
Here are my thoughts:

1) The initial submission wasn't well-thought - I will take the blame for that one
2) to counter (1) -- there was no feedback or resistance to the initial PR ([here](https://github.com/ZDoom/gzdoom/pull/2650/files)) -- hence why we arrive where we are right now :P
3) But I _also_ understand that people have busy lives, mistakes can be made, etc...
4) ... which leads me to my final point on why I think this is OK -- no one is using this feature and GZDoom 4.13 is shortlived due to some critical oversights. And I consider this particular thread also another oversight and am taking responsibility to quickly rectify it before it gets widespread.

**Comment by Blue-Shadow** [comment]
Searching the wiki for the added flags yielded nothing, luckily, which adds to the feature's obscurity.

**Comment by madame-rachelle** [comment]
Well the longer this goes unaddressed the more likely the Streisand effect will take hold, so if this isn't addressed later today I will just merge it.

**Pull request merged**
