### PR TITLE
Max draw distance setting

### PR DESCRIPTION
**Pull request by dileepvr**
Added the ability to not draw any node in the BSP whose bounding box is farther from the viewpoint than a `maxdrawdist` value from `struct Flevellocals`. Works in both hardware and software renderer modes.

Demo of speed up in Frozen Time bridge scene on a 12-year old CPU: https://www.youtube.com/watch?v=2oUUpMxDngc
`maxdrawdist` can be supplied from `MAPINFO` lump as well as changed from console live. It will persist through saved games. Default is set to `-1`, and won't activate unless greater than `0`.

The absence of drawn regions will show up as void space with clearbuffer color (normally controlled by the existing CVar `r_clearbuffer`). If using fog, this color can be set to match the local or global fog fade color by either setting the `LEVEL3_VOIDFADETOFOG` flag (set `voidfadetofog` in `MAPINFO` lump) or setting `r_clearbuffer` to `5`.

I wish I knew how to just replace the void space with a sky box but couldn't figure it out.

### CODE REVIEW

**Comment by MajorCooke** [comment]
Uh, wrong video?

**Comment by dileepvr** [comment]
Err... fixed. (That could have gotten so wrong)

Yes. Both `maxdrawdist` (float) and `voidfadetofog` (flag) can be set in mapinfo.

**Comment by MajorCooke** [comment]
The console cvar overrides the mapinfo option then?

**Comment by MajorCooke** [comment]
Watching the video, a couple things came to mind.

1. I think the fog options should be moved to Display options, gameplay options is for affecting actual gameplay and not visuals.
2. Can those cvars be made as options in the menus as well? Could be another option set in the display menus, along with a simple toggle cvar switch to quickly turn it on/off?

**Comment by dileepvr** [comment]
The Fog Effect thing is just a mod I was using. It isn't part of the commit.

I'll need to think about a menu option for toggling maxdrawdist and clearbuffer color and get back to you. Trivially done of course, but I hope others chime in as well. I stumbled on `r_clearbuffer` already existing.

**Comment by MajorCooke** [comment]
Oh! Can you show me where that mod is?

**Comment by dileepvr** [comment]
Fog Effects by Sergeant Mark IV (standalone version of whatever BD uses, I think): https://www.moddb.com/mods/brutal-doom/addons/fog-effects

**Comment by MajorCooke** [comment]
Thanks!

> The Fog Effect thing is just a mod I was using. It isn't part of the commit.
> 
> I'll need to think about a menu option for toggling maxdrawdist and clearbuffer color and get back to you. Trivially done of course, but I hope others chime in as well. I stumbled on `r_clearbuffer` already existing.

That's fair, it's merely a suggestion because it fits with being able to toggle fog on and off. Just figured having an easy switch would be nice. "On", "Off", and "Map Based" (or "Default" if you want to keep to the naming convention for Allow Jump/Crouch)

**Comment by inkoalawetrust** [comment]
So does the fog not automatically turn on if the subsector cull distance is enabled? The map needs to either have VOIDFADETOFOG or you need to type r_clearbuffer 5 to the console?

Because if that's how it works right now then it feels like an oversight IMO. The game looks pretty bad with just the plain culling. And most maps won't have the flag to replace culled geometry with fog on. Which is a problem because people will use this to make otherwise large and slow maps run faster. You basically demonstrated this with Frozen Time, it obviously doesn't have the map flag on, but people will use the render distance CVAR/setting to run the map faster, and it'll have no fog unless they know to type a very specific command in, which they probably WON'T know how to do.

So I think the behavior of VOIDFADETOFOG should probably be on by default whenever a maximum render distance is set.

**Comment by dileepvr** [comment]
It is actually a little worse than that. It is setting the void color to `viewPoint.sector->Colormap.FadeColor`. So unless the map maker put some fog in, or a mod was used to put fog in like I did, the void will be black not matter what CVARs are set. But you are right. `VOIDFADETOFOG` should probably be on by default.

I don't know if the engine should be fogging up the map by itself (after checking for existing fog density to be zero, and setting it to one everywhere). That is how mid-late 90s' 3D games did it I think?

**Comment by dileepvr** [comment]
The void now gets the fog/fade color by default (as per request) unless a level flag is set or `gl_fogmode  == 0`. I even add a `maxdrawdist` dependent weak fog density to all sectors that don't explicitly have an even higher fogdensity set. And I add a black `FadeColor` to all sector colormaps that don't have one if `maxdrawdist > 0.0`. It reverts to regular defaults if `maxdrawdist` is reset to `<= 0.0` at any time through the console.

I am also setting a maximum value for `skyfog` (density) in the level when `maxdrawdist > 0.0`. This "solved" the sky pop-in problem by making it invisible.

**Comment by MajorCooke** [comment]
Can you record a quick video to show it in action? I'm curious.

**Review by SafinW — APPROVED** [review]

**Comment by dileepvr** [comment]
Video of auto-fog/fade effect: https://youtu.be/hfmrBEGH9Dg

I am not happy with this. I need to make the fog only turn on in the last 10% of the draw distance, and work with enhanced vision modes. But that will require intervention in the shader code.

**Comment by dileepvr** [comment]
Soft, late-kick-in fog boundary, so the closer fog density is lower by 10x: https://youtu.be/n4GktOPwp_w

Required an if-block in the main fragment shader.
I can't make lightAmp and other enhanced vision modes see the fog since `isFullbrightScene()` gets called in too many places.

**Comment by RicardoLuis0** [comment]
would it be at all possible to, optionally, make the render distance adjust itself based on current FPS vs monitor refresh rate?

**Comment by dileepvr** [comment]
You mean an actual performance mode that can be toggled from the options menu? I don't know how to read the monitor refresh rate, but could probably copy the `CalcFps()` from `d_main.cpp` to wherever I need and adjust the draw distance every second (or every tic) by some percentage until a lower threshold is satisfied. Or it has two rates, and it is always slowly trying to get bigger over time, but aggressively shrinks when fps drops.

What does this look like from a UI perspective? The Options menu has an On/Off option for "Performance Mode", a number value for "Minimum FPS," and a color picker for "fog color"? And should I allow `maxdrawdist` to become `-1.0` to disable it if the fps is high enough? Because disabling will cause the skybox to show up again, making it visually jarring. We could declare, "no skies in performance mode" even though rendering skies themselves were never the performance killer.

**Comment by dileepvr** [comment]
The other issue might be the something like nuts.wad isn't slow because of geometry, but merely because of too many actors. And a naive user toggling the performance mode will see no difference. I don't want any of this to affect playsim. Would a simple renaming like "performance rendering" help?

**Comment by RicardoLuis0** [comment]
>  something like nuts.wad isn't slow because of geometry, but merely because of too many actors
it's not slow because of too many actors _ticking_, but because of too many actors _rendering_, so yes, this would help

**Comment by RicardoLuis0** [comment]
> always slowly trying to get bigger over time, but aggressively shrinks when fps drops.

yeah, that

> We could declare, "no skies in performance mode" even though rendering skies themselves were never the performance killer.

oh, i didn't realize that this _completely_ disabled skyboxes, that might be a deal breaker yeah

**Comment by MajorCooke** [comment]
I think this could be resolved if there is a flag that could be set for sectors, something akin to "dont cull", that way when users set this up they know to use it. Either that, or also performing distance checks from sky viewpoints as well and determining if they should be rendered or not.

**Comment by dileepvr** [comment]
!! I meant to close this.
I need a better understanding of how skies get applied to walls when they are left untextured. Something like that will need to be leveraged to make the sky fill the void. It would also auto apply when there is a sky above, meaning culling indoors will not throw it in.
Ultimately, lzdoom's approach of doing a distance check on linedefs and having them block out the clipper might be a better approach than rejecting nodes on the BSP tree that are too far away. I'm proud of the rapid-onset fog though. Will use that somewhere.

**Pull request closed without merging**
