### PR TITLE
Add support for animated images loading

### PR DESCRIPTION
**Pull request by Cacodemon345**
This PR adds support for creating animated textures from animated images.

### CODE REVIEW

**Review by RicardoLuis0 — APPROVED** [review]

**Review by coelckers — CHANGES_REQUESTED** [review]
No TArrays in FImageSource. please. All this is statically allocated from a memory arena so if you need more, allocate it from there, too. You can use a TArrayView to avoid handling a naked pointer.

Also, what's the ANIMDEFS extension for?

**Comment by Cacodemon345** [comment]
That ANIMDEFS extension is for making animated images loading explicit and also to preserve compatibility with prior texture packs that unknowingly use APNG (when it is implemented). I felt that it belonged best as part of ANIMDEFS since it's where animations are defined; making it implicit would open up abuse factors.

**Comment by Cacodemon345** [comment]
Switched arrays to `std::vector`.

**Review by coelckers — CHANGES_REQUESTED** [review]
When I said 'no TArrays' I didn't mean to replace them with std::vector but to remove dynamic allocation entirely out of the image system. The way it manages memory these will cause a genuine problem because the simple approach of 'just flush the memory arena' won't work anymore.

There's also something else: Is there a realistic scenario where animated images have different offsets? That case isn't even well supported now in the renderer and I am fairly certain that any delta-based animated format cannot deal with it to begin with

I am also a bit sceptical about having to explicitly enable the animation. This actually guards against an extreme fringe case - GIF hasn't been in wide use, WebP is a new feature and if there's APNG that slipped in by accident they should be a very rare exception that doesn't warrant such an inconvenience.

**Comment by Cacodemon345** [comment]
`std::vector` members in FImageSource and derived classes allocate from ImageArena now.

**Comment by Cacodemon345** [comment]
Another reason for making animation enabling explicit is because GZDoom and Raze doesn't share a common texture animation system, and the texture manager code was written with the assumption of `single image lump = single texture` in mind, so I have to make it explicit in the appropriate place.

**Comment by Cacodemon345** [comment]
Marked as draft while I investigate crashes.

**Comment by prof-hastig** [comment]
If you want my two cents, for god's sake, please drop animated GIF support!
The format is old and really should be discontinued ASAP, not be promoted to first class support by adding more third party baggage to the project.

Frankly, the way you are fumbling around here does not generate much confidence in the result.

**Comment by inkoalawetrust** [comment]
The result is fine, WebP works pretty much flawlessly now as does GIF, now that caco fixed the crashing and freezing I was experiencing. But the GIF support needs to go, WebP is literally just a better GIF format. And while it's not as common or easy to make as GIF, it's nowhere near as obscure as say, IVF is. You can literally find online WebP converters. If WebP was half as obtuse as IVF, then GIF support _would've_ been more desirable.

**Review by coelckers — CHANGES_REQUESTED** [review]
I finally managed to do a review of this thing. Unfortunately it is still not usable. When I said 'no TArrays' I meant is should statically allocate all its memory, but now there's std::vectors with custom allocators that perform even worse!

All this data should be statically allocated (and not be resized as it is being built.)

For now I am putting this feature on hold

**Pull request closed without merging**
