### PR TITLE
Synchronize movie audio playback

### PR DESCRIPTION
**Pull request by kcat**
A very preliminary start to getting audio playback to synchronize with movies.

This first step is simply replacing the `VpxPlayer`'s use of the music system for the soundtrack with a custom sound stream. It doesn't do any synchronization yet, it should act just the same as before. But with this, I'll be able to extend `SoundStream` to report back the audio playback position, which can be used with the (constantly updating) clock time specified to the `Frame` method to work out how far behind or ahead the audio may be, which can then in turn be used by the SoundStream callback to skip or duplicate samples to have the audio at the correct position relative to the video.

The main thing to be aware of here is that, at first it will only synchronize the audio track that's picked up along side a VPX video file (e.g. `movies/foo.ivf`+`movies/foo.opus`). I shouldn't have too much problem extending this to work with Smacker's built-in audio track, and Interplay MVE files' built-in audio track should be doable too.

Sounds that are set to trigger on particular frames, such as those defined like
```
Outro
{
    Video = "movies/foo.ivf"
    Sound = "foo"
}
```
will not synchronize, as it's treated as a fire-and-forget sound effect (like if you were doing a scripted sequence and called `A_StartSound` at a particular time). The only way I can see around this limitation is to have some way for a sound to be defined to trigger on frame 0 (all video players seem to start checking at frame 1 for sound triggers, so anything set for frame 0 would never play), and treat that as a sound/music stream instead of a sound effect trigger. Although I don't know what complications there may be by treating a sound set in the animation's sound list as a music stream instead of a sound effect.

This is a rather bare-bones start, I know, but I figure it's best to make sure I'm not making a fundamental problem before going too far.

### CODE REVIEW

**Comment by kcat** [comment]
I implemented basic synchronization for VPX movies that use a soundtrack (the `movies/foo.ivf`+`movies/foo.opus` style of video with audio). It seems to be working decently, but there is an issue I noticed that `MoviePlayer::Frame` doesn't seem to get called as often as would be ideal. This causes the stream to sometimes think it's running ahead because the frame clock is an old value, skip backwards, then notice it's running behind after the frame clock updates, and skip forward.

Is the value passed to `MoviePlayer::Frame` based on some other clock that I could use more directly? Like `std::steady_clock`? What options are there to get more precise timing of the movie clock aside from what's periodically provided to `MoviePlayer::Frame`?

**Comment by coelckers** [comment]
> Is the value passed to MoviePlayer::Frame based on some other clock that I could use more directly? Like std::steady_clock? What options are there to get more precise timing of the movie clock aside from what's periodically provided to MoviePlayer::Frame?

The value is based on the game ticker with interpolation applied. Indirectly it is based on I_nsTime but don't expect the values of those two to properly corellate. What precisely do you need here?

**Comment by kcat** [comment]
> The value is based on the game ticker with interpolation applied. Indirectly it is based on I_nsTime but don't expect the values of those two to properly corellate. What precisely do you need here?

Turns out it was a red herring. I thought the issue was `MoviePlayer::Frame` wasn't getting called often enough with new clock times, but it turns out it's getting called plenty with updated values. The problem was the arbitrary buffer size value I was giving to `S_CreateCustomStream` was causing very occasional stutters/underruns given how often the stream is updated. I should do something about that, but using a more reasoned buffer stream size seems to fix the problem.

**Comment by kcat** [comment]
Everything's in place now for intended synchronization behavior. If anyone else can test it to make sure it's working for them, that would be helpful (again to note, this is currently only for ivf/vpx+sound file pairs, not other formats yet or using an Outro block with a sound definition).

If everything's satisfactory, it can either be merged and I'll work on other formats afterward, or I can try to get Smacker files to use synchronized audio tracks first before merging. Or if there's anything else you want done, I can work on whatever that may be.

**Comment by kcat** [comment]
Actually, looking at the smacker decoder, it will be a bit more involved than I initially thought. It's certainly doable, but it has the same fundamental concern as other formats with video and audio together, that being the audio needs to be read and decode at its own pace, separate from the video. This is generally done by reading in the packets from the file as a separate step and putting the encoded data into separate queues for each stream, then each video and audio stream can read and decode their packet data as needed.

Alternatively, each video and audio stream can open its own file handle, where each can read through the file independently and only take the data they need. This is kind of kludgy, but would require the least amount of effort.

In any case, this PR is doing what it's supposed to for ivf+audio file pairs, so it is ready to review and merge if it's good enough. If you'd prefer to have Smacker and Interplay videos handled before merging, and/or figure out a way to use certain sound triggers as a music stream first, let me know.

**Comment by kcat** [comment]
I had enough time to work on Smacker files. They should now have audio properly synchronized with video. Though I only have one test file (out of everything ffmpeg can do, it can't encode Smacker files for me to make more test files).

**Comment by kcat** [comment]
And that should do it. MvePlayer for Interplay MVE videos now does synchronized audio too, so all movie players that can use an audio track should play them properly synchronized.

Note that I really didn't have much to test for MVE files, the only ones I could get my hands on didn't even originally work (they use uncompressed audio, where `InterplayDecoder` assumed compressed, and they don't use the supported video data format). But I got it to the point where the audio plays while having junk video, so I know the audio is playing as it should while the display is updating. I'm not sure exactly which games GZDoom supports that uses MVE files, but it should be tested with those games to make sure nothing's broken.

**Comment by coelckers** [comment]
The only mve file in those games is the intro movie of Redneck Rampage Rides Again.
If you need that for testing I can send it to you.

**Comment by coelckers** [comment]
I'm going ahead and merge this anyway so I can run some tests with it. I

**Comment by coelckers** [comment]
I decided to revert it all again and reject the PR in this form. 
It constantly mucks around with the audio which results in audible distortion. I even noticed in the low quality soundtrack of RRRA's intro. I wasn't able to play any video that did not constantly skip or duplicate blocks of sound.

IMO the audio stream should be allowed to play uninterrupted, unless the gap becomes too large to compensate, adjusting the video would be far less disruptive than this.

**Pull request merged**
