### PR TITLE
Update LZMA SDK to 23.01

### PR DESCRIPTION
**Pull request by Cacodemon345**
This PR updates LZMA SDK to 23.01.

As a bonus, this PR adds support for XZ-compressed (LZMA2 with filters applied) files in ZIP archives.

### CODE REVIEW

**Review by alexey-lysiuk — COMMENTED** [review]
1. Are you sure that all newly added files are needed, like `Aes*.*`, `Sha256*.*`, a bunch of `*Enc.*`?
2. PR doesn't compile with GCC 7. Please make sure that all targets are green before making a pull requests.

**Comment by madame-rachelle** [comment]
I also think it's important to consider does this update solve any important issues? Considering that we are close to a release it seems a bit pointless to be pushing such things right at the moment.

**Comment by coelckers** [comment]
This won't get merged before the release for sure. Concerning GCC 7, is that still relevant. We eventually want to move to C++20, I'm not sure if that compiler can do it.

**Comment by Cacodemon345** [comment]
1. GCC 7 shouldn't be relevant anymore (Ubuntu 18.04 is EOL, Ubuntu 20.04 ships with GCC 9).

2. Only `Sha256*.*` files should be needed for XZ checksum calculation. The encoder and encryption files can be safely removed.

3. As for important issues, it would be support for LZMA2 filters, which is absent in the older LZMA SDK and needed to decompress 7z archives using them.

Regardless, I am fine with this getting merged after 4.11 releases.

**Comment by coelckers** [comment]
I suspected as much for GCC 7. Ubuntu18.04 is no longer relevant and I'd like to move on to C++20, and as this shows, it seems to not be able to compile valid production code anymore.

**Pull request merged**
